# LOG4J configuration
log4j.rootLogger=DEBUG, Appender2,SchedulerLog,MailLog
 
#log4j.appender.Appender1=org.apache.log4j.ConsoleAppender
#log4j.appender.Appender1.layout=org.apache.log4j.PatternLayout
#log4j.appender.Appender1.layout.ConversionPattern=%-7p %d [%t] %c %x - %m%n
 
log4j.appender.Appender2=org.apache.log4j.RollingFileAppender
#log4j.appender.Appender2.File= ${catalina.home}/logs/perfexlog.log  
log4j.appender.Appender2.File=C\:/Perfex360/PerfexLogs/perfexlog.log  
log4j.appender.Appender2.Append=true
log4j.appender.Appender2.MaxFileSize=100KB
log4j.appender.Appender2.MaxBackupIndex=3 
log4j.appender.Appender2.layout=org.apache.log4j.PatternLayout
log4j.appender.Appender2.layout.ConversionPattern=%-7p %d [%t] %c %x - %m%n

#log4j.category.debugLogger=TRACE, debugLog
log4j.appender.MailLog=org.apache.log4j.RollingFileAppender
#log4j.appender.Appender2.File= ${catalina.home}/logs/perfexlog.log  
log4j.appender.MailLog.File=C\:/Perfex360/PerfexLogs/MailLog.log
log4j.appender.MailLog.Append=true
log4j.appender.MailLog.MaxFileSize=100KB
log4j.appender.MailLog.MaxBackupIndex=3 
log4j.appender.MailLog.layout=org.apache.log4j.PatternLayout
log4j.appender.MailLog.layout.ConversionPattern=%-7p %d [%t] %c %x - %m%n

log4j.appender.SchedulerLog=org.apache.log4j.RollingFileAppender
log4j.appender.SchedulerLog.File=C\:/Perfex360/PerfexLogs/SchedulerLog.log
log4j.appender.SchedulerLog.Append=true
log4j.appender.SchedulerLog.MaxFileSize=100KB
log4j.appender.SchedulerLog.MaxBackupIndex=3 
log4j.appender.SchedulerLog.layout=org.apache.log4j.PatternLayout
log4j.appender.SchedulerLog.layout.ConversionPattern=%-7p %d [%t] %c %x - %m%n