QfmfDetecteddate-required=["dteQfmfDetecteddate","Enter Detected Date"]
QfmfDetectedby-required=["cmbQfmfDetectedby","Select Detected By"]
QfmfPhenomenaid-required=["cmbQfmfPhenomenaid","Select Phenomena"]
QfmfProblem-required=["txtQfmfProblem","Enter Problem"]
QfmfMethod-required=["txtQfmfMethod","Enter Method"]
QfmfCountermeasure-required=["txtQfmfCountermeasure","Enter Counter Measure"]
QfmfResponsibility-required=["txtQfmfResponsibility","Enter Responsibility"]
QfmfStatus-required=["cmbQfmfStatus","Enter Status"]
QfmfTargetdate-required=["dteQfmfTargetdate","Enter Target Date"]
QfmfCompletedby-required=["txtQfmfCompletedby","Enter Completed By"]
QfmfCompleteddate-required=["dteQfmfCompleteddate","Enter Completed Date"]

