
#AbnmSectionid-required=["cmbAbnmSectionid","Select Section"]
AbnmCellid-required=["err_cell","Select JH"]
#AbnmEquipmentid-required=["cmbAbnmEquipmentid","Select Equipment"]
AbnmTradeid-required=["cmbAbnmTradeid","Select Maintenance Section"]
AbnmDescription-required=["txtAbnmDescription","Enter Abnormality Description"]
AbnmTypeid-required=["cmbAbnmTypeid","Select Abnormality Type"]
AbnmTagclassid-required=["cmbAbnmTagclassid","Select Tag"]
#AbnmAssemblyid-required=["cmbAbnmAssemblyid","Select Assembly"]
AbnmStatus-required=["cmbAbnmStatus","Select Status"]
AbnmCountermeasure-required=["txtAbnmCountermeasure","Enter Counter Measure"]
AbnmCompletedby-required=["cmbAbnmCompletedby","Select Completed By"]
AbnmWoendtime-required=["dteAbnmWoendtime","Select Completed Date"]
AbnmDetectedby-required=["cmbAbnmDetectedby","Select Detected By"]
AbnmDetectiondate-required=["dteAbnmDetectiondate","Enter Detected Date"]
AbnmDetectiondate-GE=["dteAbnmDetectiondate","Detected Date Cannot be greater  than current Date"]
AbnmDetectiondate-LECD=["dteAbnmDetectiondate","Detection Date Cannot be be greater  than current Date"]
AbnmWostarttime-LE=["dteAbnmWoendtime","Work Start Date Cannot be less than Detected Date"]
AbnmWoendtime-LE=["dteAbnmWoendtime","Completed Date Cannot be less than Work Start Date"]
AbnmWoendtime-LECD=["dteAbnmWoendtime","Completed Date Cannot be be greater  than current Date"]
#Abnwostartdatetime-LE=["dteAbnmWostarttime","Work Start Date Cannot be less than Allotted Date"]
AbnmCategoryid-required=["cmbAbnmCategoryid","Select ABN Category"]
AbnmImpactid-required=["cmbAbnmImpactid","Select Abnormality Impact"]
#AbnmWhatcause-required=["txtAbnmWhatcause","Enter What Cause"]
#AbnmWhyabnhappened-required=["txtAbnmWhyabnhappened","Enter Why ABN Happened"]
#AbnmContaminant-required=["txtAbnmContaminant","Enter Abnormality Contaminant"]
AbnmMode-required=["txtAbnmMode","Enter Abnormality Mode"]
AbndImprovementteam-required=["cboAbndImprovementteam","Select Improvement Team"]
COMPLETED=["Completed Abnormality cannot be Deleted"]
MAXCOMPDATE=["COMPLETED DATE EXCEEDS THE LIMIT"]
msrOverlap=["MSR Overlap"]
ACTIONPLAN_PENDING=["Complete all Action Plans to complete Abnormality"]
UK_ABN_TL_ABNORMALITY=["This Record is already exist"]
#AbnmFactoryid-required=["cmbFactory","Select Factory"]                                