SiemEmpmKeyid-required=["cmbSiemEmpmKeyid","Select Employee"]
SiemInjuryModeid-required=["cmbSiemInjuryModeid","Select Injury Type"]
SiemInjuryTypeid-required=["cmbSiemInjuryTypeid","Select Injury Type"]
SiemBodypart-required=["cmbSiemBodypart","Select Location"]
ContractEmp-required=["txtContractEmployee","Enter Contract Employee"]
ContractComp-required=["txtSiemCompany","Enter Contract Company"]
UK_SINC_EMPM_MODE_BODY=["This Record is already exist"]
