AplmWhatprobdesc-required=["txtAplmWhatprobdesc","Enter Action Plan"]
AplmWhendate-required=["dteAplmWhendate","Select When Date"]
AplmActivitydesc-required=["txtAplmActivitydesc","Enter Activity"]
AplmReason-required=["txtAplmReason","Enter Reason"]
AplmCompletdby-required=["cmbAplmCompletdby","Select Completed By"]
AplmCompleteddate-required=["dteAplmCompleteddate","Select Completed Date"]
AplmTargetdate-LE=["dteAplmTargetdate","Date Should be lesser than Target Date"]
AplmApprovedby-required=["cmbAplmApprovedby","Select Approved By"]
AplmApproveddate-required=["cmbAplmApproveddate","Select Approved Date"]
AplmLocationid-required=["cmbAplmLocationid","Select Location"]
AplmCompleteddate-LE=["dteAplmCompleteddate","Date Should Be Greater Than Approved Date"]
AplmCompleteddate-LECD=["dteAplmCompleteddate","Date Should Not Be Greater Than Current Date"]
AplmApproveddate-LECD=["dteAplmApproveddate"," Approved Date Should Not Be Greater Than Current Date"]
AplmApproveddate-LE=["dteAplmApproveddate","Approved Date Should Not Be Lesser Than Allotted Date"]