FvasAreaname-required=["txtFvasAreaname","Enter Audit Area Name"]
FvasResponsibiltyid-required=["cmbFvasResponsibiltyid","Select Team Leader"]
FvasCircleid-required=["cmbFvasCircleid","select Circle"]
FK_FVAD_FVAS_KEYID=["This RECORD Is Being Referred"]