BdmsRelatedto-required=["cmbbdmsRelatedto","Select Related To"]
BdmsFactoryid-required=["cmbbdmsFactoryid","Select Factory"]
BdmsSectionid-required=["cmbbdmsSectionid","Select Section"]
BdmsCellid-required=["cmbbdmsCellid","Select Cell"]
BdmsMachineid-required=["cmbbdmsMachineid","Select Equipment"]
BdmsMould-required=["cmbbdmsMould","Select Mould"]
BdmsReporteddate-required=["dtebdmsReporteddate","Select Occured Date"]
BdmsPriority-required=["cmbbdmsPriority","Select Priority"]
BdmsAssemblyid-required=["cmbbdmsAssemblyid","Select Assembly"]
BdmsFinalphenomena-required=["cmbbdmsFinalphenomena","Select Phenomena"]
BdmsBookedby-required=["cmbbdmsBookedby","Select Booked By"]
BdmsShiftid-required=["cmbbdmsShiftid","Select Shift Id"]
BdmsBookedtrade-required=["cmbbdmsBookedtrade","Select Maint. Section"]
BdmsActualworktime-required=["dtebdmsWostarttime","Enter Work Start & End Details"]
BdmsProblemdescription-required=["txtbdmsProblemdescription","Enter Problem Description"]
BdmsCompleteddate-required=["dtebdmsCompleteddate","Enter Completed Date"]
#BdanCostcentre-required=["cmbbdanCostcentre","Select Cost Center"]
BdmsProdaccepdate-GECD=["dtebdmsProdaccepdate","Production start date should not less than current date"]
BdmsOtherPhenomena-required=["txtbdmsOtherPhenomena","Enter Phenomena"]


BdanFailuretype-required=["cmbbdanFailuretype","Select Failure Type"]
BdanOtherFailuretype-required=["txtbdanOtherFailuretype","Enter Failure Type"]
BdanClassificationid-required=["cmbbdanClassificationid","Select Classification"]
BdanCompletedby-required=["cmbbdanCompletedby","Select Analysed By"]
Woendtime-required=["chbWoendtime"]
BdmsWostarttime-LE=["dtebdmsWostarttime","Work Start should be lesser than Production Acceptance Date"]
BdmsWostarttime-LECD=["dtebdmsWostarttime","Select Work Start Time"]
BdmsWoendtime-LE=["dtebdmsWoendtime","Work End should be lesser than Production Acceptance Date"]
BdmsReceiveddate-LECD=["dtebdmsReceiveddate","Select Received Date"]
BdmsWostartflag-required=["chbbdmsWostartflag","Select Work Start Time"]
BdmsWoendflag-required=["chbbdmsWoendflag","Select Work End Time"]
UndefinedPhen=["This BD has Undefined Phenomena.Do You want to raise the proposal?"] 
MAXCOMPDATE=["COMPLETED DATE EXCEEDS THE LIMIT"]
msrOverlap=["MSR Overlap"]
prodAccept=["Production Accepted.Cannot be delete."]
ActionPlan=["Action Plan pending"]