BachName-required=["txtBachName","Enter Name"]
#BachCode-required=["txtBachCode","Enter Code"]
BachProgKeyid-required=["cmbBachProgKeyid","Select program"]
BachVenuKeyid-required=["cmbBachVenuKeyid","Select venue"]

BachMinsize-required=["txtBachMinsize","Enter Minimum Size"]
BachMaxsize-required=["txtBachMaxsize","Enter Maximum Size "]
BachFromdate-required=["dteBachFromdate","Select From date"]
BachTilldate-required=["dteBachTilldate","Select Till date"]
BachTilldate-LE=["dteBachTilldate"," From date should be lesser than Till date"]
BachMaxsize-GE=["txtBachMaxsize","Minimum size should be lesser than Maximum Size"]


