LgfrDefsyspassword-invalid=["txtcpwdOldpwd","Invalid Password"]
LgfrDefsyspassword-match=["txtcpwdNewpwd","New Password Should not be same as Old Password"]
LgfrConfpassword-invalid=["txtcpwdConfpwd","Confirm Password Should  be equal as New Password"]
LgfrOldpassword-invalid=["txtcpwdOldpwd","Invalid Password"]
CpwdOldpwd-required=["txtcpwdOldpwd","Enter Old Password"]
CpwdNewpwd-required=["txtcpwdNewpwd","Enter New Password"]
CpwdConfpwd-required=["txtcpwdConfpwd","Enter Confirm Password"]