ClisMachineid-required=["cmbClisMachineid","Select Equipment"]
ClisStandard-required=["txtClisStandard","Enter Standard"]
ClisNextduedate-required=["dteClisNextduedate","Select NEXT DUE Date"]
#ClisActivitytype-required=["cmbClisActivitytype","Select Classification"]
#ClisWherelocation-required=["txtClisWherelocation","Enter Main Part"]
#ClisShiftid-required=["cmbClisShiftid","Select Shift"]
ClisWhatactivity-required=["txtClisWhatactivity","Enter Item"]
#ClisResponsibilityid-required=["cmbClisResponsibilityid","Select Responsibility"]
ClisCreatedby-required=["cmbClisCreatedby","Select Responsibility"]
ClisHowmuchduration-required=["txtClisHowmuchduration","Enter Time"]
#ClisTime-required=["txtClisTime","Select Shift Time"]
ClisHowmethod-required=["txtClisHowmethod","Enter How Method"]
ClisFrequencyunit-required=["cmbClisFrequencyunit","Select Frequency"]
#ClisEffectivedate-required=["dteClisEffectivedate"," Select Effective"]
ClisEffectivedate-GE=["dteClisEffectivedate"," Effective Date must be lesser then next due date"]
actual_msg=!-------!No Actual Value available!-------!
	
	
	
	
	
	
	
	
		