DckiInvoiceno-required=["txtDckiInvoiceno","Enter Invoice No."]
DckiTargetdate-LE=["dteDckiTargetdate","Target Date should  be greater than Inspection Date"]
DckiDate-LECD=["dteDckiDate","Select Date"]
DckiAnalyseddate-LE=["dteDckiAnalyseddate","Analysed Date should  be greater than Inspection Date"]
UK_DCKI_INVOICENO=["Invoice No. already Exists"]
DiamDoneby-required=["cmbDiamDoneby","Select Done By"]
DiamDate-required=["dteDiamDate","Select Date"]
DiamQtmdoneby-required=["cmbDiamQtmdoneby","Select Done By"]
DiamQtmdate-required=["dteDiamQtmdate","Select Date"]