Qaudinvoiceno-required=["txtQaudinvoiceno","Enter Invoice No"]
Qaudpono-required=["txtQaudpono","Enter Po No"]
Qaudquantity-required=["txtQaudquantity","Enter Quantity"]
Qauddatetime-required=["dteQauddatetime","Enter Date"]
Qaudcustomerid-required=["cmbQaudcustomerid","Select Customer"]
Qaudbacthno-required=["txtQaudbacthno","Enter Batch/Lot No"]
Qaudworkorderno-required=["cmbQaudworkorderno","Select Work Order No"]
Qaudprdmid-required=["cmbQaudprdmid","Select Part No"]
Qaudinspectedby-required=["txtQaudinspectedby","Enter Inspected By"]
Qaudreviewedby-required=["txtQaudreviewedby","Enter Reviewed By"]
Qaudauditstatus-required=["Qaudauditstatus","Select Audit Status"]
FK_MCEM_MACHINEID=["This RECORD Is Being Referred"]
Qauddatetime-LECD=["Date and Time Cannot be greater than Today Date and Time"]
