
SdamFlid-required=["cmbSdamFlid","Enter the Function Location "]
SdamMembers-required=["txtSdamMembers","Enter the Members"]
SdamRemarks-required=["txtSdamRemarks","Enter the Remarks "]
SdamDate-required=[""dteSdamDate","Enter the Audit Date"]
SdamDoneby-required=["cmbSdamDoneby","Select the Audit DoneBy"]