SiemEmpmKeyid-required=["cmbSineEmpmKeyid","Select Employee"]
SiemInjuryModeid-required=["cmbSineInjuryModeid","Select Injury Type"]
SiemInjuryTypeid-required=["cmbSineInjuryTypeid","Select Injury Type"]
SiemBodypart-required=["cmbSineBodypart","Select Location"]
ContractEmp-required=["txtContractEmployee","Enter Contract Employee"]
ContractComp-required=["txtSineCompany","Enter Contract Company"]
UK_SINM_EMPM_MODE_BODY=["This Record is already exist"]
