EmpmName-required=["txtEmpmName","Enter Name"]
EmpmCode-required=["txtEmpmCode","Enter Code"]
EmpmEmployeenumber-required=["txtEmpmEmployeenumber","Enter EmployeeNumber"]
EmpmJoineddate-required=["dteEmpmJoineddate","Select Date"]
EmpmDepartmentid-required=["cmbEmpmDepartmentid","Select Department"]
EmpmDesignationid-required=["cmbEmpmDesignationid","Enter Designation"]
EmpmTradeid-required=["cmbEmpmTradeid","Select Maint.section"]
EmpdBirthdate-LECD=["dteEmpdBirthdate","Select past date "]
UK_EMPM_CODE=["Code already Exist"]
UK_EMPM_EMPLOYEENUMBER=["Employee Number already Exist"]
FK_ABNM_DETECTEDBY=["This RECORD is being referred "]
LOGIN_EXISTS=["Login ID exists for the user! Delete from user master !!"]
EmpmJoineddate-LE=["dteEmpdBirthdate","Birth date must be lesser then Join Date"]
EmpmJoineddate-LECD=["dteEmpmJoineddate","select Pass date"]
EmpmCompany-required=["cmbEmpmCompany","select Company"]
EmpmLocation-required=["cmbEmpmLocation","select Location"]
EmployeeCategory=[{"id":"R","text":"EMPLOYEE"},{"id":"A","text":"ASSOCIATE"},{"id":"C","text":"CONTRACT"},{"id":"M","text":"MANAGER"},{"id":"B","text":"BADLI"},{"id":"T","text":"TRAINEE"},{"id":"E","text":"EXECUTIVE"},{"id":"O","text":"OTHERS"}]
