#AsmdProgKeyid-required=["cmbAsmdProgKeyid,"Select Program"]
#AsmdBachKeyid-required=["cmbAsmdBachKeyid","Select Batch"]
AsmmEvaluationDesc-required=["txtAsmmEvaluationDesc","Enter Evaluation Desc"]
AsmmEvaluationDate-required=["dteAsmmEvaluationDate","Select Evaluation Date"]
AsmdTopiKeyid-required=["cmbAsmdTopiKeyid","Select Topic"]
AsmdResult-required=["cmbAsmdResult","Select Result"]
#AsmdScore-required=["txtAsmdScore","Enter Score"]
AsmmEvaluationDate-LECD=["dteAsmmEvaluationDate","Evaluation Date Cannot be greater than Current Date "]
PreEvaluationdate-LE=["dteAsmmEvaluationDate","Evaluation Date Cannot be Less than Pre Assessment Date"]
AsmmEvaluationDate-GE=["dteAsmmEvaluationDate","Evaluation Date Cannot be greater than Post Assessment Date"]
EvalDateExist=["dteAsmmEvaluationDate","Evaluation Exist For This Day"]
