BflkBachKeyid-required=["cmbBflkBachKeyid","Select Batch"]
BflkFtymKeyid-required=["cmbBflkFtymKeyid","Select Faculty"]
Bstdbachkeyid-required=["cmbBstdbachkeyid","Select Batch"]
FK_ASCL_CHEK_KEYID=["Check List Already Linked"]


