SkilCode-required=["txtSkilCode","Enter Skill Code"]
SkilName-required=["txtSkilName","Enter Skill Name"]
SkilParentid-required=["cmbSkilParentid","Select Skill Parent"]
SkilFactKeyid-required=["cmbSkilFactKeyid","Select Factory"]
SkilEvaluationtypeid-required=["cmbSkilEvaluationtypeid","Select Skill Evaluation Parameter"]
SkilType-required=["cmbSkilType","Select Skill Type"]
FK_ERSL_SKIL_KEYID=["This RECORD Is Being Referred"]
FK_ERSR_SKIL_KEYID=["This RECORD Is Being Referred"]
UK_SKILL_NAME=["This Skill Name Already Assigned For This Factory"]
FK_PRTS_SKIL_KEYID=["This RECORD Is Being Referred"]
