selectType =  [{"id":"B","text":"BEHAVIOR"},{"id":"K", "text":"KNOWLEDGE" },{"id":"S", "text":"SKILL" }]
KSA =  [{"id":"A","text":"ATTITUDE"},{"id":"K", "text":"KNOWLEDGE" },{"id":"S", "text":"SKILL" }]
