FactCompanyid-required=["cmbFactCompanyid","Select Company"]
FactName-required=["txtFactName","Enter Name"]
FactCode-required=["txtFactCode","Enter Code"]
FactAddress-required=["txtFactAddress","Enter Address"]
UK_FACT_CODE = ["Code Already Exist"]