equipmentGroup_input.eqg=selectEquipmentGroup-false-GEN_TL_EQPGROUPMST-EQGM_KEYID-EQGM_ACTIVE-GEN_TL_FUNCTIONALLOCN-FNLN_ORIGINALID
emp_input.emp=selectEmployee-false-GEN_TL_EMPLOYEEMST-EMPM_KEYID-EMPM_ACTIVE-GEN_TL_FUNCTIONALLOCN-FNLN_ORIGINALID
Utility_input.uty=selectUtility-false-GEN_TL_TOOLSMST-GEN_TL_FUNCTIONALLOCN-FNLN_ORIGINALID
Tools_input.uty=selectTools-false-GEN_TL_TOOLSMST-TOLM_KEYID-TOLM_ACTIVE-GEN_TL_FUNCTIONALLOCN-FNLN_ORIGINALID
cell_input.cell=selectCell-true-GEN_TL_CELLMST-CELL_KEYID-CELL_ACTIVE-GEN_TL_FUNCTIONALLOCN-FNLN_ORIGINALID
section_input.sect=selectSection-true-GEN_TL_SECTIONMST-SECT_KEYID-SECT_ACTIVE-GEN_TL_FUNCTIONALLOCN-FNLN_ORIGINALID
shift_input.sftm=selectShift-false-GEN_TL_SHIFTMST-SFTM_KEYID-SFTM_ACTIVE-GEN_TL_FUNCTIONALLOCN-FNLN_ORIGINALID
company_input.comp=selectCompany-true-GEN_TL_COMPANYMST-COMP_KEYID-COMP_ACTIVE-GEN_TL_FUNCTIONALLOCN-FNLN_ORIGINALID
assembly_input.asb=selectAssembly-true-GEN_TL_ASSEMBLYMST-ASSM_KEYID-ASSM_ACTIVE-GEN_TL_FUNCTIONALLOCN-FNLN_ORIGINALID
factory_input.fact=selectFactory-true-GEN_TL_FACTORYMST-FACT_KEYID-FACT_ACTIVE-GEN_TL_FUNCTIONALLOCN-FNLN_ORIGINALID
location_input.locn=selectLocation-true-GEN_TL_LOCATIONMST-LOCN_KEYID-LOCN_ACTIVE-GEN_TL_FUNCTIONALLOCN-FNLN_ORIGINALID
EmployeeCost_input.ec=selectEmployeeCost-false-GEN_TL_EMPLOYEECOST-EMPC_KEYID-EMPC_ACTIVE-GEN_TL_FUNCTIONALLOCN-FNLN_ORIGINALID

#UtilityCost_input.ec=selectUtilityCost-false-GEN_TL_TOOLSMST
#ContractorCost_input.ec=selectContractorCost-false-WOM_TL_CONTRACTORMST

