HolmName-required=["txtHolmName","Enter Name"]
HolmFactory-required=["cmbHolmFactory","Select Factory"]
HolmDescription-required=["txtHolmDescription","Enter Description"]
HolmDate-required=["dteHolmDate","Select Date"]
UK_GEN_TL_HOLIDAYMST=["ID already Exist"]
#BeanDay-required=["cboBeanDay","Select Day"]