ImrgCharacteristicid-required=["cmbImrgCharacteristicid","Select Characteristic id"]
ImrgProductid-required=["cmbImrgProductid","Select Product id "]
ImrgUpperlimit-required=["txtImrgUpperlimit","Select Upper limit"]
UK_IMRCHARACTERISTCONFIG=["Data Already Exists"]
