QirmInspectionid-required=["","Select Inspected By"]
QirmInspectiondate-required=["","Select Inspected Date"]
QirmInspectedshiftid-required=["","Select Inspected Shift"]
QirmInspectionqty-required=["","Enter Inspected Qty"]
QirdProcessid-required=["","Select Process"]
QirdSubprocessid-required=["","Select Sub-Process"]
QirdPhenomenaid-required=["","Select Phenomena"]
Qird4mtype-required=["","Select 4M Type"]
QirmProductid-required=["","Select Product"]
QirdQuantity-required=["","Enter Quantity"]
QirdType-required=["","Select Type"]
view_Mode=["Data cannot be saved in view mode"]
FK_QIRM_INSPECTIONID=["Select Inspected By"]
FK_QIRM_INSPECTEDSHIFTID=["Select Inspected Shift"]
#PK_PCS_TL_OPERATORDTL=["Operator Name Already Exists"]
QsbrQuantity-required=["","Enter Quantity"]
QsbrRemarks-required=["","Enter Remarks"]
ExceedInspectedQty=["Should not Exceed Inspected Qty"]
ExceedTotalQty=["Should not Exceed Total Qty"]

sel_Details=["Select Process, Subprocess, Phenomena"]