JhamFlid-required=["cmbJhamFlid","Select Functional Location"]
JhamJhstepid-required=["cmbJhamJhstepid","Select Approval Level"]
JhamAuditteamid-required=["cmbJhamAuditteamid","Select Audit Template"]
JhamAuditorname-required=["txtJhamAuditorname","Enter Auditor Name"]
JhamAuditortype-required=["cboJhamAuditortype","Select Audit Type"]
JhamLeadername-required=["txtJhamLeadername","Enter Members"]
JhamTotalpoints-required=["txtJhamTotalpoints","Enter Total Points"]
JhamAuditdate-required=["dteJhamAuditdate","Select Date"]
JhamAuditdate-LECD=["dteJhamAuditdate","Audit Date Should Be Less Than Or Equal To Current Date"]

