JhamMachineid-required=["cmbJhamMachineid","Select Equipment"]
JhamAuditteamid-required=["cmbJhamAuditteamid","Select Audit Level"]
JhamAuditorname-required=["txtJhamAuditorname","Enter Auditor Name"]
JhamAuditortype-required=["cboJhamAuditortype","Select Audit Type"]
JhamLeadername-required=["txtJhamLeadername","Enter Leader Name"]
JhamTotalpoints-required=["txtJhamTotalpoints","Enter Total Points"]

JhamAuditdate-required=["dteJhamAuditdate","Select Date"]


