JhkzCellid-required=["cmbJhkzCellid","Select Line"]
JhkzMachineid-required=["cmbJhkzMachineid","Select Machine"]
JhkzFactoryid-required=["cmbJhkzFactoryid","Select Factory"]
JhkzDescription-required=["txtJhkzDescription","Enter Description"]
JhkzImplementedby-required=["cmbJhkzImplementedby","Select Implemented By"]
JhkzImplementeddate-required=["dteJhkzImplementeddate","Select Implemented Date"]
