JhapTemplatename-required=["txtJhapTemplatename","Enter Name"]
JhapTemplatecode-required=["txtJhapTemplatecode","Enter Code"]
JhapAudittype-required=["cmbJhapAudittype","Select Audit Type"]
JhapAuditlevel-required=["cmbJhapAuditlevel","Select Audit Level"]
JhapRevisionno-required=["txtJhapRevisionno","Enter Revision No"]
JhapRevisiondate-required=["dteJhapRevisiondate","Select Date"]
JhapRevisiondate-LECD=["dteJhapRevisiondate","Revision Date Should Be Less Than Or Equal To Current Date"]
UK_JHA_TL_AUDITPARAMETER=["This Template Already Exists"]
FK_JHAM_AUDITTEAMID =["Data have been referred"]
FK_JHAD_PARAMETERID =["This Parameter have been referred"]