JhapTemplatename-required=["txtJhapTemplatename","Enter Name"]
JhapTemplatecode-required=["txtJhapTemplatecode","Enter Code"]
JhapRevisionno-required=["txtJhapRevisionno","Enter Revision No"]
JhapRevisiondate-required=["dteJhapRevisiondate","Select Date"]
