KznmDate-required=["dtekznmDate","Enter Date"]
KznmFlid-required=["kznmfunLocation","Select DMT"]
KznmTheme-required=["txtkznmTheme","Enter Theme"]
KznmPreparedid-required=["cmbkznmPreparedid","Select Requested By"]
KznmTarget-required=["txtkznmTarget","Enter Target"]
KznmBenchmark-required=["txtkznmBenchmark","Enter Benchmark"]
KznmStartdate-required=["dtekznmStartdate","Enter Start Date"]
KznmEnddate-required=["dtekznmEnddate","Enter End Date"]
KznmEnddate-LE=["dtekznmEnddate","End Date Should not be Less than Start Date"]
KznmEnddate-GECD=["dtekznmEnddate","End date Should be Greater than Current Date"]
KznmStartdate-LECD=["dtekznmStartdate","Start Date Should be Less than current Date"]
KznmStartdate-LE=["dtekznmStartdate","Start Date Should be Less than End Date"]
KznmEnddate-GE=["dtekznmEnddate","End Date Should be Greater than Start Date"]
KznmKpiid-required=["cmbkznmKpiid","Select KPI"]
results-required-AtLeastOne=["txtresultArea","Select Benefit Area"]
KznmCompleteddate-required=["dtekznmCompleteddate","Enter Completion Date"]
KznmCompletedid-required=["cmbkznmCompletedid","Select Completed By"]
KznmActivitypillarid-required=["cmbKznmActivitypillarid","Select Activity Pillar"]
KznmPresentproblem-required=["txtkznmPresentproblem","Enter Present/Status"]
KznmCompleteddate-LECD=["dtekznmCompleteddate","Completed Date Cannot Be Greater than Current Date"]
UK_KZN_TL_MST=["This Record is already exist"]
#KznmWwmsKeyid-required=["cmbkznmWwmsKeyid","Enter Analysis"]
#KznmMaterialcost-required=["err_txtkznmMaterialcost","Enter Material Cost"]
#KznmLabourcost-required=["err_txtkznmLabourcost","Enter Labour Cost"]
#KznmCellid-required=["cmbkznmCellid","Select Cell"]
#KznmMachineid-required=["cmbkznmMachineid","Select Equipment"]
#KznmMouldid-required=["cmbkznmMouldid","Select Mould"]