#KinkIndicatorname-required=["txtKinkIndicatorname","Enter Name"]
#KinkIndicatorcode-required=["txtKinkIndicatorcode","Enter Code"]
#KinkParentid-required=["cmbKinkParentid","Select Parent Id"]
#KinkInputtype-required=["cmbKinkInputtype,"Select Input Type"]
#KinkInputentry-required=["cmbKinkInputentry","Select Input Entry"]
#KinkIdentifier-required=["txtKinkIdentifier","Enter Identifier"]
#KinkDeptKeyid-required=["cmbKinkDeptKeyid","Select Responsibility"]
#KinkCostarea-required=["cmbKinkCostarea","Select Cost Area"]
#KinkManualcalctype-required=["cmbKinkManualcalctype","Select Manual Entry Actual"]
KinkImpactarea-required=["cmbKinkImpactarea","Select Impact Area"]
KinkFrequency-required=["cmbKinkFrequency","Select Frequency"]
#ENT_TL_TRAININGAREA_UK=["This Topic Already Added For This Parent"]
KinkKpireason-required=["txtKinkKpireason","Enter Reason for Tracking KPI"]
KinkDescription-required=["txtKinkDescription","Enter KPI Description"]
KinkInputtype-required=["cmbKinkInputtype","Select Type of Input"]
KinkInputentry-required=["cmbKinkInputentry","Select Data Type"]
KinkPillarid-required=["cmbKinkPillarid","Select Data Type"]
KinkUomid-required=["cmbKinkUomid","Select UOM"]
UK_KPI_TL_INDICATOR_KK=["This Identifier Already Exists"]
UK_PILLARID_NAME=["Indicator Description Already Exists"]
FK_KAUK_DEPTID=["Indicator Already Referred In Target/Actual Entry"]
FK_KIDL_INDICATORID=["Indicator Referred In Functional Location, Could Not Able To Delete"]