

	LgfrUsernamelength-required=["txtlgfrUsernamelength","Enter User Name Length"]
	LgfrMinpasslength-required=["txtlgfrMinpasslength","Enter Min PassWord Leng"]
	LgfrMaxpasslength-required=["txtlgfrMaxpasslength","Enter Max Password Leng"]
	LgfrAlphabets-required=["txtlgfrAlphabets","Enter No Of Alphabets"]
	
	LgfrNumerals-required=["txtlgfrNumerals","Enter No Of Numerals"]
	LgfrPasschangegap-required=["txtlgfrPasschangegap","Enter Password Change Gap"]
	LgfrPasschangefreq-required=["txtlgfrPasschangefreq","Enter Password Change Freq"]
	LgfrPassgraceperiod-required=["txtlgfrPassgraceperiod","Enter Password Grace Period"]
	
	LgfrPassintimation-required=["txtlgfrPassintimation","Enter Password Intimation"]
	LgfrMincharpasschange-required=["txtlgfrMincharpasschange","Enter Password Min Char"]
	LgfrFailedloginattempts-required=["txtlgfrFailedloginattempts","Enter No of Failed Attempts"]
	LgfrPasshistoryremember-required=["txtlgfrPasshistoryremember","Enter No of Password History Remember"]
	
	LgfrPassneverexpires-required=["cmblgfrPassneverexpires","Enter Password Never Expires"]
	LgfrIsloginaudit-required=["cmblgfrIsloginaudit","Enter Is Login Audit"]
	LgfrIspassaudit-required=["cmblgfrIspassaudit","Enter Is Password Audit"]
	LgfrIsprivaudit-required=["cmblgfrIsprivaudit","Enter Is Priv Audit"]
	
	LgfrDefsyspassword-required=["txtlgfrDefsyspassword","Enter Default Password"]
	
	selectpsdexp  = [{"id":"Y","text":"YES"},{"id":"N","text":"NO"}]
	selectlgadt = [{"id":"Y","text":"YES"},{"id":"N","text":"NO"}]
	selectpasadt = [{"id":"Y","text":"YES"},{"id":"N","text":"NO"}]
	selectprvadt = [{"id":"Y","text":"YES"},{"id":"N","text":"NO"}]
	
	maxpwdlenght =["txtcpwdNewpwd","Password Should Be Maximum <Minnumber> Character "]
	minpwdlenght =["txtcpwdNewpwd","Password Should Be Minimum  <Maxnumber> Character "]
	minAlphabets =["txtcpwdNewpwd","Password Should have Minimum Alphabets <Minaph> Character "]
	minnumeric =["txtcpwdNewpwd","Password Should have Minimum Numeric <Minnum> Number "]