LoemLocacategoryid-required=["cmbLoemLocacategoryid","Select the Category"]
LoemOccurencedatetime-required=["dteLoemOccurencedatetime","Select Occured Date & Time"]
LoemPrepareddatetime-required=["dteLoemPrepareddatetime","Select Prepared Date & Time"]
LoemLopcdesc-required=["txtLoemLopcdesc","Enter the LOPC Description"]
LoemEmployeeid-required=["cmbLoemEmployeeid","Select the Employee Id"]
LoemIdentifiedby-required=["cmbLoemIdentifiedby","Select the Prepared By"]
			  