RasmFlid-required=["txtRasmFlid","Select Functional Location"]
RasmArea-required=["txtRasmArea","Enter Area"]
RasmTitle-required=["txtRasmTitle","Enter Title"]
RasmDate-required=["dteRasmDate","Enter Date"]
RasmDate-LECD=["dteRasmDate","Risk Assessment Date Should Be Less Than Or Equal To Current Date"]
RasmPreparedby-required=["cmbRasmPreparedby","Select Prepared By"]
FK_MAND_RASD_KEYID=["Delete Management program for this Risk Assessment"]