Mldmdescription-required=["txtMldmdescription","Enter Description"]
Mldmowner-required=["cmbMldmowner","Select Owner"]
Mldmslno-required=["txtMldmslno","Enter SLNo"]
Mldmnoofcavities-required=["txtMldmnoofcavities","Enter No of Cavities"]
Mldmtype-required=["cmbMldmtype","Select type"]
Mldmmouldstatus-required=["cmbMldmmouldstatus","Select MouldStatus"]
Mldmcurrentlocation-required=["cmbMldmcurrentlocation","Select Current Location"]

