MunlMachineid-required=["cmbmunlMachineid","Enter Machine"]
MunlRelatedto-required=["cmbmunlRelatedto","Select Related To"]
MunlShiftdate-required=["dtemunlShiftdate","Select Shift Date"]
MunlShift-required=["cmbmunlShift","Select Shift"]
MunlStationid-required=["cmbmunlStationid","Select Assembly/Station"]
MunlPhenid-required=["txtmunlPhenid","Enter Reason"]
MunlActivitytype-required=["cmbmunlActivitytype","Select Activity type"]
MunlReason-required=["txtmunlReason","Enter Reason for Unloading"]
MunlTargetdate-required=["dtemunlTargetdate","Select Target Date"]
MunlTargetdate-LE=["dtemunlTargetdate","<span>Target Date Should Be</span><br> Greater or Equal to Booked Date"]
MunlReportedby-required=["cmbmunlReportedby","Select Reported By"]
MunlStatus-required=["cmbmunlStatus","Select Status"]
MunlCompletedby-required=["cmbmunlCompletedby","Select Completed By"]
MunlWostartdate-required=["dtemunlWostartdate","Select Work Start Date"]
MunlWostartdate-LE=["dtemunlOccureddate","WorkStartDate must be Greater or Equal to Booked Date"]
MunlWoenddate-required=["dtemunlWoenddate","Select Work End Date"]
MunlWoenddate-LE=["dtemunlWoenddate","Work End Date must be Greater or Equal to Work Start Date"]
MunlMouldid-required=["cmbmunlMouldid","Select Mould Id"]
MunlFactoryid-required=["cmbmunlFactoryid","Enter Factory"]
MunlAction-required=["txtmunlAction","Enter Action"]
lossDuration=["Loss Duration Should be Equal to Downtime"]
MAXCOMPDATE=["COMPLETED DATE EXCEEDS THE LIMIT"]
msrOverlap=["MSR Overlap"]