
MpsmCause-required=["txtmpsmCause","Enter Cause"]
MpsmProblem-required=["txtmpsmProblem","Enter Problem"]
MpsmCostcentreid-required=["cmbmpsmCostcentreid","Select Cost Center"]
MpsmBeforeimprovement-required=["txtmpsmBeforeimprovement","Enter Before Improvement"]
MpsmAfterimprovement-required=["txtmpsmAfterimprovement","Enter After Improvement"]
MpsmImprovementtheme-required=["txtmpsmImprovementtheme","Enter Theme"]
MpsmCreateddate-required=["dtempsmCreateddate","Enter Date"]
MpsmCellid-required=["cell","Select Cell"]
MpsmIscosteffective-required=["err_chkmpsmIscosteffective","Select Is Cost Effective"]     
MpsmCompletedby-required=["cmbmpsmCompletedby","Select Completed By"] 
MpsmCompleteddate-required=["dtempsmCompleteddate","Enter Completion Date"] 
MpsmCompletedremarks-required=["txtmpsmCompletedremarks","Enter Completed Remarks"]           