NmrnSeveritypotentialid-required=["cmbNmrnSeveritypotentialid","Select Near Miss Category"]
NmrnOccurrencedatetime-required=["dteNmrnOccurrencedatetime","Select Occurrence Date & Time"]
NmrnEmployeeid-required=["cmbNmrnEmployeeid","Select Employee Name"]
NmrnDescnearmiss-required=["txtNmrnDescnearmiss","Enter Description Of Near Miss"]
NmrnIdentifiedby-required=["cmbNmrnIdentifiedby","Select Prepared By"]
NmrnPrepareddatetime-required=["dteNmrnPrepareddatetime","Select Prepared Date & Time"]


			  