EtcmLocation-required=["EtcmLocation","Select Location"]
EtcmTopicid-required=["cmbEtcmTopicid","Select Topic"]
EtcmAnchoredby-required=["cmbEtcmAnchoredby","Select Anchored By"]
EtcmTrainingfunction-required=["cmbEtcmTrainingfunction","Select ET Function"]
EtcmCalendarDate-required=["dteEtcmCalendarDate","Select Date"]
EtcmMaxDuration-required=["txtEtcmMaxDuration","Select Duration"]
EtcmTopiccategory-required=["cmbEtcmTopiccategory","Topic Category"]
UK_ETCU_ROLE_KEYID=["This Unique Position Already Exists!"];

			  