OlseFlid-required=["LossEntryfunLocation","Select Functional Location"]
OlseDate-required=["dteOlseDate","Select Date"]
OlseLossid-required=["cmbOlseLossid","Select Loss"]
ExcelName-required=["cmbExcelName","Select File to Upload"]