BphmName-required=["txtBphmName","Enter Phenomena Name"]
BcsmName-required=["txtBcsmName","Enter Cause Name"]
BphmAssemblyid-required=["cmbBphmAssemblyid","Select Assembly"]
BphmPhenomenaname-required=["txtBphmPhenomenaname","Enter Phenomena Name"]
BcsmPhenomenaid-required=["cmbBcsmPhenomenaid","Select Phenomena"]
UK_BDM_TL_PHNCAUSELINK=["Phenomena already Exist"]
UK_BPHM_PHENOMENANAME=["Phenomena Name already Exist"]
UK_BCSM_NAME=["Cause Name already Exist"]

