MttrFlid-required=["cmbMttrFlid","Select Functional Location"]
MttrMachineid-required=["cmbMttrMachineid","Select Machine"]
MttrDate-required=["dteMttrDate","Enter Date"]
MttrProcess-required=["txtMttrProcess","Enter Process"]
MttrTradeid-required=["cmbMttrTradeid","Select Trade"]
MttrVersion-required=["txtMttrVersion","Enter Version No"]
MttrDescription-required=["txtMttrDescription","Enter Description"]
MttrStdsetuptime-required=["txtMttrStdsetuptime","Enter Standard Setup Time"]
MttrExistingTime-required=["txtMttrExistingTime","Enter Existing Internal Time"]
MttrConvertedTime-required=["txtMttrConvertedTime","Enter Converted External Time"]
MttrSavingTime-required=["txtMttrSavingTime","Enter Saving Time"]
MttrRemarks-required=["txtMttrRemarks","Enter Remarks"]
MttrStatus-required=["cmbMttrStatus","Select Status"]

MttdSlno-required=["txtMttdSlno","Enter SlNo."]
MttdTask-required=["txtMttdTask","Enter Task"]
MttdImprovement-required=["txtMttdImprovement","Enter Improvement Details"]
MttdItExtFromtime-required=["txtIntExistFromTimeHrs,txtIntExistFromTimeMins,txtIntExistFromTimeSecs","Enter Existing Internal From Time"]
MttdItExtTotime-required=["txtIntExistToTimeHrs,txtIntExistToTimeMins,txtIntExistToTimeSecs","Enter Existing Internal To Time"]
MttdEtExtFromtime-required=["txtExtExistFromTimeHrs,txtExtExistFromTimeMins,txtExtExistFromTimeSecs","Enter Existing External From Time"]
MttdEtExtTotime-required=["txtExtExistToTimeHrs,txtExtExistToTimeMins,txtExtExistToTimeSecs","Enter Existing External To Time"]
MttdPossibleForConv-required=["chkYes","Check Possible For Conversion"]
MttdPossibleForConv-required-dependent=["txtMttdImprovement","Enter Improvement Details"]
MttdEtNewFromtime-required=["txtIntFromTimeHrsNew","Enter New From Time(External)"]
MttdEtNewTotime-required=["txtIntToTimeHrsNew","Enter New To Time(External)"]
MttdTotalInternalTime-required=["txtMttdConvertedTime","Total Internal Time"]
MttdTotalExternalTime-required=["txtMttdTotalExternalTime","Total External Time"]
MttdTotalExternalNewTime-required=["txtMttdTotalExternalNewTime","Enter Total External New Time"]
MttdRespoinsibility-required=["cmbMttdRespoinsibility","Select Responsibility"]
MttdTargetdate-required=["dteMttdTargetdate","Enter Target Date"]
MttdCompletedby-required=["cmbMttdCompletedby","Select Completed By"]
MttdCompleteddate-required=["dteMttdCompleteddate","Enter Completed Date"]
MttdStatus-required=["cmbMttdStatus","Select Status"]
MttdRemarks-required=["txtMttdRemarks","Enter Remarks"]
UK_MTTD_SLNO=["This SlNo Already Exists"]
CK_MTTD_IT_TIME=["Existing Internal From Time Should Be Greater Than To Time"]
CK_MTTD_ET_TIME=["Existing External From Time Should Be Greater Than To Time"]
CK_MTTD_ET_NEW_TIME=["External New From Time Should Be Greater Than To Time"]
MttdTargetdate-LE=["dteMttdTargetdate","Target Date Cannot be less than MTTR Date"]
MttdCompleteddate-LE=["dteMttdCompleteddate","Completed Date Cannot be less than MTTR Date"]
CK_COMPLETED=["Complete All Details"]

			  
			  