CriaFlid-required=["cmbCriaFlid","Select Functional Location"]
CriaName-required=["CriaName","Enter Name"]
CriaMinimumpoints-required=["txtCriaMinimumpoints","Enter Minimum Points"]
CriaMaximumpoints-required=["txtCriaMaximumpoints","Enter Maximum Points"]
			  