PMAdherenceMainGrid={"rowHeaders":[["KEYID","","","","","","","","","","","","",""],["KEYID","Equipment","July  ","July","August","August","September","September","October","October","November","November","December","December"],["KEYID","Equipment","%","Cummulative","%","Cummulative","%","Cummulative","%","Cummulative","%","Cummulative","%","Cummulative"]],"tableHeight":"70%%","rowNumbers":"true","tableWidth":"105%%","tableButton":"false","sortable":"false","colModel":[{"index":"KEYID","hidden":"false","width":"225","name":"KEYID","editable":"false"},{"index":"Equipment","hidden":"false","width":"230","name":"Equipment","editable":"false","align":"left"},{"index":"Percentage1","hidden":"false","width":"100","name":"Percentage1","editable":"false","align":"right"},{"index":"Cummulative1","hidden":"false","width":"80","name":"Cummulative1","editable":"false","align":"right"},{"index":"Percentage2","hidden":"false","width":"100","name":"Percentage2","editable":"false","align":"right"},{"index":"Cummulative2","hidden":"false","width":"80","name":"Cummulative2","editable":"false","align":"right"},{"index":"Percentage3","hidden":"false","width":"100","name":"Percentage3","editable":"false","align":"right"},{"index":"Cummulative3","hidden":"false","width":"100","name":"Cummulative3","editable":"false","align":"right"},{"index":"Percentage4","hidden":"false","width":"100","name":"Percentage4","editable":"false","align":"right"},{"index":"Cummulative4","hidden":"false","width":"100","name":"Cummulative4","editable":"false","align":"right"},{"index":"Percentage5","hidden":"false","width":"100","name":"Percentage5","editable":"false","align":"right"},{"index":"Cummulative5","hidden":"false","width":"100","name":"Cummulative5","editable":"false","align":"right"},{"index":"Percentage6","hidden":"false","width":"100","name":"Percentage6","editable":"false","align":"right"},{"index":"Cummulative6","hidden":"false","width":"200","name":"Cummulative6","editable":"false","align":"left"}]}















