
PmsdAssemblyid-required=["cmbPmsdAssemblyid","Select AssemblyId"]
PmsdSource-required=["chkPmsdSource","select Internal/External"]
PmsdTradeid-required=["cmbPmsdTradeid","Select Maintenance Section"]
PmsdActivitytype-required=["cmbPmsdActivitytype","Select ActivityType"]
PmsdMachinecondition-required=["cmbPmsdMachinecondition","Select Machine Condition"]
PmsdDuration-required=["txtPmsdDuration","Enter Duration"]
PmsdActivity-required=["txtPmsdActivity","Enter Activity"]
PmsdHowmethod-required=["txtPmsdHowmethod","Enter Method"]
PmsdPreparedbyid-required=["cmbPmsdPreparedbyid","Select Prepared BY"]
CmdtUomid-required=["cmbCmdtUomid","Select UoM"]
CmdtInspectionid-required=["cmbCmdtInspectionid","Select Inspection "]
PmsdTarget-GE=["txtPmsdMinValue","Target value should be greater than or equal to MIN value"]
PmsdTarget-LE=["txtPmsdTarget","Target value should not be greater than or equal to MAX value"]
PmsdMaxValue-GE=["txtPmsdMaxValue","MAX value should be greater than or equal to MIN value"]
PmsdMinValue-LE=["txtPmsdMinValue","MIN value should be less than or equal to MAX value"]
			
			
			
		    