
PkymPokayokeno-required=["txtpkymPokayokeno","Enter Poka Yoke No"]
PkymProblem-required=["txtpkymProblem","Enter Problem"]
PkymSolution-required=["txtpkymSolution","Enter Solution"]
PkymPresentdesc-required=["txtpkymPresentdesc","Enter Present Description"]
PkymAfterdesc-required=["txtpkymAfterdesc","Enter After Description"]
PkymMachineid-required=["cmbpkymMachineid","Select Machine"]
Type-required-AtLeastOne=["chkDetection","Select Type"]
Function-required-AtLeastOne=["chkWarning","Select Function"]
Effect-required-AtLeastOne=["chkBreakdown","Select Effect On"]