QammTitle-required=["txtQammTitle","Enter Title"]
QammFlid-required=["","Select Function Location"]
QammDate-required=["dteQammDate","Date should be less than or Equal to Current Date"]
UK_CTQ_DEFECT=["Defect Name Already Exists for CTQ"]
ACTPLN_PENDING=["Action Plan is Pending, Can not Completed Ten Step"]
ASSEMENT_PENDING=["Impact Assessment is Pending, Can not Completed Ten Step"]
UK_PROCESS_CTQ=["Record Already Exists for the combination of CTQ, Grade Spec, Process and Date"]
FK_QTM_TL_TS_CHECKPOINTS=["Reference Exists, Check Point Can not be Deleted"]