	CfemSupplierid-required=["cmbCfemSupplierid","Select Supplier"]
	CfemProductid-required=["cmbCfemProductid","Select Part Name"]
	CfemMaterialtype-required=["txtCfemMaterialtype","Select Material type"]
	CfemDcno-required=["txtCfemDcno","Enter DC No."]
	CfemDate-required=["dteCfemDate","Select Date"]
	CfemGentolerance-required=["txtCfemGentolerance","Enter General tolerance"]
	CfemQtyreceived-required=["txtCfemQtyreceived","Enter Qty Recieved"]
	CfemUomid-required=["txtCfemUomid","Enter Uom"]
	CfemSamplesize-required=["txtCfemSamplesize","Enter Sample Size"]
	CfemRevison-required=["txtCfemRevison","Enter Revision"]
	CfedSpecification-required=["cmbCfedSpecification","Enter Specification"]
	CfedActual1-required=["txtCfedActual1","Enter Actual1"]
	CfedActual2-required=["txtCfedActual2","Enter Actual2"]
	CfedActual3-required=["txtCfedActual3","Enter Actual3"]
	CfedResult-required=["txtCfedResult","Enter Result"]