	FqcmProcessid-required=["cmbFqcmProcessid","Select Process"]
	FqcmProductid-required=["cmbFqcmProductid","Select Part Name"]
	FqcmMachineid-required=["cmbFqcmMachineid","Select Machine"]
	FqcmDrawingno-required=["txtFqcmDrawingno","Enter Drawing No."]
	FqcmShiftid-required=["cmbFqcmShiftid","Select Shift"]
	FqcmDate-required=["dteFqcmDate","Select Date"]
	FqcdParameter-required=["cmbFqcdParameter","Enter Parameter"]
	FqcdSpecification-required=["cmbFqcdSpecification","Enter Specification"]