SwpmFlid-required=["cmbSwpmFlid","Select Functional Location"]
SwpmIssuedate-LECD=["dteSwpmIssuedate","Date Should be lesser than equal to Current Date"]
SwpmPrepareddate-LECD=["dteSwpmPrepareddate","Prepared Date Should be lesser than equal to Current Date"]
SwpmPreparedby-required=["cmbSwpmPreparedby","Select Prepared by"]
SwpmActivity-required=["txtSwpmActivity","Enter Activity"]
SwpmCheckpoints-required=["txtSwpmCheckpoints","Enter Check Points"]