SftlFlid-required=["cmbfstlkFlnid","Select Functional Location"]
SftlDate-required=["dtesftlDate","Select  date"]
SftlPrepardby-required=["cmbsftlPrepardby","Select Prepared by "]
SftlTalk-required=["txtsftlTalk","Enter Safety Talk"]