Activity-required=["txtActivity","Enter the Activity"]
Members-required=["txtMembers","Enter the Members"]
Responsibility-required=["cmbResponsibility","Select Doneby"]
Date-required=["dteDate","choose the Date"]