SftmDuration-required=["spnSftmDuration","Select Duration"]
SftmName-required=["txtSftmName","Enter Name"]
SftmCode-required=["txtSftmCode","Enter Code"]
SftmShiftorder-required=["cmbSftmShiftorder","Select ShiftOrder"]
SftmStarttime-required=["spnSftmStarttime","Select StartTime"]
SftmBreaktime-required=["txtSftmBreaktime","Enter BreakTime"]
