SirmFlid-required=["SkillIndexRPfunLocation","Select Function Location"]
SirmRoleKeyid-required=["cmbSirmRoleKeyid","Select Type "]
SirdSpokKeyid-required=["cmbSirdSpokKeyid","Select Criteria"]
SirdReviewno-required=["cmbSirdSpokKeyid","Enter Review Point"]
SirdReviewpoint-required=["cmbSirdSpokKeyid","Enter Review Point"]
SiamFlid-required=["SkillAssementfunLocation","Select Function Location"]
SiamUniqueposid-required=["cmbSiamUniqueposid","Select Type "]
SiamReviewdate-required=["dteSiamReviewdate","Select Review Date"]

UN_SIRD_REVIEWPOINT=["Review Point Already Exists"]
UK_SUBREVIEWNO=["Review No. Already Exists"]
EN_SPOKID=["Select Criteria "]
EN_REVIEWPOINT=["Enter Review Point "]
EN_REVIEWNO=["Enter Review No "]
FK_SIAD_REVIEWID=["Reference Exists, Review Point Can not be Delete."]