Employee=[{"id":"EMP001" ,"text":"Ramu"},{"id":"EMP002" ,"text":"Azeem"},{"id":"EMP003" ,"text":"SUNDER"},{"id":"EMP004" ,"text":"Zuveria"},{"id":"EMP005" ,"text":"Kiran"}]

SupportType=[{"id":"B" ,"text":"BCM"},{"id":"D" ,"text":"DEVELOPMENT"},{"id":"SD" ,"text":"SERVICE DESK"},{"id":"PS" ,"text":"PERFEX SUPPORT"},{"id":"T" ,"text":"PERFEX 360"}]

IssueType=[{"id":"SP" ,"text":"Slow Performance"},{"id":"B" ,"text":"Bug"},{"id":"NR" ,"text":"New Requirement"},{"id":"PS" ,"text":"PerfexSupport"}]
 
 IssueLocation=[{"id":"B" ,"text":"BCM "},{"id":"T" ,"text":"Tribeni"},{"id":"K" ,"text":"kovai"},{"id":"D" ,"text":"Dhq"},{"id":"C" ,"text":"chennai"}]


IssueStatus=[{"id":"P" ,"text":"Pending"},{"id":"C" ,"text":"Completed"},{"id":"w" ,"text":"WorkinProgress"},{"id":"H" ,"text":"Hold"}]










