SusmFlid-required=["cmbSusmFlid"," Select Functional Location"]
SusmDate-LECD=["dteSusmDate"," Date Should be lesser than equal to Current Date"]
SusmPreparedby-required=["cmbSusmPreparedby","Select Prepared by"]
SusmParticipants-required=["cmbSusmParticipants","Select Participants"]
SusmDescription-required=["txtSusmDescription","Enter Description"]
SusdConformance-required=["txtSusdConformance", "Enter Conformance"]
SusdNonconformance-required=["txtSusdNonconformance","Enter NonConformance"]