TfmsTitle-required=["txttfmsTitle","Enter Title"]
TfmsDate-required=["dtetfmsDate","Select Date"]
TfmsDuration-required=["txttfmsDuration","text Duration"]
TfmsFaculty-required=["cmbtfmsFaculty"," Select Faculty "]
TfmsParticipantname-required=["cmbtfmsParticipantname","Select Participant name"]
TfmsDesignation-required=["cmbtfmsDesignation","Select Designation"]
TfmsRemarks-required=["txttfmsRemarks","Enter Remarks"]
TfmsFlid-required=["TrainingFBfunLocation","Select Functional Location"]

