PunsMachineid-required=["cmbpunsMachineid","Select Equipment"]
PunsSectionid-required=["cmbpunsSectionid","Select Section"]
PunsAssemblyid-required=["cmbpunsAssemblyid","Select Assembly"]
PunsTradeid-required=["cmbpunsTradeid","Select Trade"]
PunsHowmuchduration-required=["txtpunsHowmuchduration","Enter Duration"]
PunsMachinecondition-required=["cmbpunsMachinecondition","Enter Condition"]
PunsWhatactivity-required=["txtpunsWhatactivity","Enter activity"]
PunsHowmethod-required=["txtpunsHowmethod","Enter How Method"]

