UpsmTitle-required=["txtUpsmTitle","Enter Title"]
UpsdRawmaterial-required=["txtUpsdRawmaterial","Enter Raw Material"]
UpsdCorrectionaction-required=["txtUpsdCorrectionaction","Enter Corrective Action"]
UpsdInformto-required=["txtUpsdInformto","Enter Inform To"]
UpsdDefect-required=["cmbUpsdDefect","Select Defect"]
UpsmDate-required=["dteUpsmDate","Select Date"]