Usrm_ccno-required=["cmbUsrm_ccno","Select ccno"]
Usrm_validfrom-GE=["dteUsrm_validfrom","From date should not be greater than To date " ]

Usrm_securitypolicyid-required=["cmbUsrm_securitypolicyid","Select Profile Id"]
Usrm_loginid-required=["txtUsrm_loginid","Enter Login Id"]
Usrm_password-required=["txtUsrm_password","Enter Password"]
Usrm_defaultpassword-required=["txtUsrm_defaultpassword","ReEnter Password"]
Usrm_Confpassword-invalid=["txtUsrm_defaultpassword","Passwords did not match"]



