VchmTitle-required=["txtVchmTitle","Title"]
VccdOrderno-required=["txaVccdOrderno","Enter Order No."]
VccdSortorder-required=["txaVccdSortorder","Enter Sort Order"]
VccdCriteria-required=["txaVccdCriteria","Enter Criteria"]
VccdCheckpoints-required=["txaVccdCheckpoints","Enter CheckPoint"]
CK_VCHD_CHECK_POINT=["Check Point Already Exist"]
UK_CHECKPONTS=["Check Point Already Exist"]
REQ_details=["Please enter Mandatory Fields"]
ABNEXIST=["Abnormality Exists, Can not delete Record"]
UK_FLID_DATE_TITLE=["Data Already Exists"]