VchmTitle-required=["txtVchmTitle","Enter Title"]

VchdCheckPoint-required=["txtVchdCheckPoint","Enter CheckPoint"]
VchdTargetScore-required=["txtVchdTargetScore","Enter Target Score"]
VchdCriteria-required=["txtVchdCriteria","Enter Criteria"]

VccdCriteria-required=["txaVccdCriteria","Enter Criteria"]
VccdCheckpoints-required=["txaVccdCheckpoints","Enter CheckPoint"]
CK_VCHD_CHECK_POINT=["Check Point Already Exists"]
UK_CHECKPONTS=["Check Point Already Exists"]
UK_CHECKPOINTS=["Check Point Already Exists"]
UK_VCHM_TITLE=["Check List Title Already Exists"]
FK_VCUD_VCHD_KEYID=["Reference Exists, Cannot be Delete"]