WofbAction-required=["txtWofbAction","Enter Action"]
WofbStartdate-required=["dteWofbStartdate","Enter Start Date"]
WofbEnddate-required=["dteWofbEnddate","Enter End Date"]
WofbEnddate-LE=["dteWofbEnddate","End date must be greater than Start Date"]
WofbStartdate-LECD=["dteWofbStartdate","Start date Should be Equal to Current Date"]
WofbProdstartdate-required=["dteWofbProdstartdate","Enter Production Start Date"]
WofbDuration-required=["txtWofbDuration","Enter Duration"]
WofbCompletedby-required=["cmbWofbCompletedby","Select Completed By"]
