verify= [{"id"\:"G","text"\:"Good"},{"id"\:"N","text"\:"Not Good"}]
factor= [{"id"\:"Y","text"\:"Yes"},{"id"\:"N","text"\:"No"}]
type= [{"id"\:"S","text"\:"Skill"},{"id"\:"K","text"\:"Knowledge"},{"id"\:"T","text"\:"Training"}]


