package com.akranta.tpm.utils;

import java.util.List;

public class PCSRownumConstants {
	
	public static final String MCHAVLTIME = "MCHAVLTIME";
	public static final String PLANNEDQTY = "PLANNEDQTY";
	public static final String PRODTIME = "PRODTIME";
	public static final String UNREPORTED = "UNREPORTED";
	public static final String NOPLAN = "NOPLAN";
	public static final String PRODANDREJCTION = "PRODANDREJCTION";
	public static final String NUMPRODUCTS = "NUMPRODUCTS";
	public static final String PARTNO = "PARTNO";
	public static final String PARTNAME = "PARTNAME";
	public static final String PRODUCTMODEL = "PRODUCTMODEL";
	public static final String CYCLETIME = "CYCLETIME";
	public static final String PRODUCEDQTY = "PRODUCEDQTY";
	public static final String DEFECTNREWORK = "DEFECTNREWORK";
	public static final String REJECTEDQTY = "REJECTEDQTY";
	public static final String REWORKQTY = "REWORKQTY";
	public static final String DEFECTTIME = "DEFECTTIME";
	public static final String REPROCESS = "REPROCESS";
	public static final String PRODUCTIONLOSS = "PRODUCTIONLOSS";
	public static final String EF = "EF";
	public static final String PEFL = "PEFL";
	public static final String UEFL = "UEFL";
	public static final String PROCESSFAILURE = "PROCESSFAILURE";
	public static final String EFJ = "EFJ";
	public static final String SETUPANDADJ = "SETUPANDADJ";
	public static final String TOOLCHANGELOSS = "TOOLCHANGELOSS";
	public static final String TOOLCHANGSUBJEC = "TOOLCHANGSUBJEC";
	public static final String TOOLCHANGEACHIV = "TOOLCHANGEACHIV";
	public static final String TOOLCHANGEBDF = "TOOLCHANGEBDF";
	public static final String STARTUPLOSS = "STARTUPLOSS";
	public static final String MS = "MS";
	public static final String SPEEDLOSS = "SPEEDLOSS";
	public static final String SHUTDOWNLOSS = "SHUTDOWNLOSS";
	public static final String JH = "JH";
	public static final String PM = "PM";
	public static final String PTRAINING = "PTRAINING";
	public static final String PMEETING = "PMEETING";
	public static final String PELECSHUTDOWN = "PELECSHUTDOWN";
	public static final String PGASSHUTDOWN = "PGASSHUTDOWN";
	public static final String PAIRSHUTDOWN = "PAIRSHUTDOWN";
	public static final String OPLANSHUTDOWN = "OPLANSHUTDOWN";
	public static final String BREAKS = "BREAKS";
	public static final String SPARETRIALEXP = "SPARETRIALEXP";
	public static final String RAWTRIALEXP = "RAWTRIALEXP";
	public static final String PROGRAMCANCEL = "PROGRAMCANCEL";
	public static final String PROGRAMHELDUP = "PROGRAMHELDUP";
	public static final String SPLTRAINING = "SPLTRAINING";
	public static final String MANAGEMENTLOSS = "MANAGEMENTLOSS";
	public static final String WAITINSTRUCTION = "WAITINSTRUCTION";
	public static final String WAITMATERIAL = "WAITMATERIAL";
	public static final String WAITPERSONAL = "WAITPERSONAL";
	public static final String WAITTUBE = "WAITTUBE";
	public static final String WAITINK = "WAITINK";
	public static final String WAITSOLVENT = "WAITSOLVENT";
	public static final String WAITVIALTRAY = "WAITVIALTRAY";
	public static final String WAITPSPLATE = "WAITPSPLATE";
	public static final String WAITLASTSHEET = "WAITLASTSHEET";
	public static final String INSPROGCHANGE = "INSPROGCHANGE";
	public static final String WAITSHERSHEET = "WAITSHERSHEET";
	public static final String WAITPARAOIL = "WAITPARAOIL";
	public static final String WAITCUTTINGOIL = "WAITCUTTINGOIL";
	public static final String WAITCAPSHELL = "WAITCAPSHELL";
	public static final String WAITWADS = "WAITWADS";
	public static final String CAPSHELL = "CAPSHELL";
	public static final String WAITPLASTICCAP = "WAITPLASTICCAP";
	public static final String WAITSEAL = "WAITSEAL";
	public static final String WAITCOLOURPP = "WAITCOLOURPP";
	public static final String WAITMASTERBASE = "WAITMASTERBASE";
	public static final String WAITPP = "WAITPP";
	public static final String COMMONUTILITY = "COMMONUTILITY";
	public static final String MOTIONLOSS = "MOTIONLOSS";
	public static final String LINEORGLOSS = "LINEORGLOSS";
	public static final String LOGISTICSLOSS = "LOGISTICSLOSS";
	public static final String MEASUREMENTLOSS = "MEASUREMENTLOSS";
	public static final String ENERGYLOSS = "ENERGYLOSS";
	public static final String DIETOOLJIGLOSS = "DIETOOLJIGLOSS";
	public static final String YIELDLOSS = "YIELDLOSS";
	public static final String REMARKS = "REMARKS";
	public static final String RESULTS = "RESULTS";
	public static final String LOADINGTIME = "LOADINGTIME";
	public static final String PRODAVLTIME = "PRODAVLTIME";
	public static final String EFFPRODMINS = "EFFPRODMINS";
	public static final String ROA = "ROA";
	public static final String ROP = "ROP";
	public static final String ROQ = "ROQ";
	public static final String OEE = "OEE";
	
	public  int rownum_MCHAVLTIME;
	public  int rownum_PLANNEDQTY;
	public  int rownum_PRODTIME;
	public  int rownum_UNREPORTED;
	public  int rownum_NOPLAN;
	public  int rownum_PRODANDREJCTION;
	public  int rownum_NUMPRODUCTS;
	public  int rownum_PARTNO;
	public  int rownum_PARTNAME;
	public  int rownum_PRODUCTMODEL;
	public  int rownum_CYCLETIME;
	public  int rownum_PRODUCEDQTY;
	public  int rownum_DEFECTNREWORK;
	public  int rownum_REJECTEDQTY;
	public  int rownum_REWORKQTY;
	public  int rownum_DEFECTTIME;
	public  int rownum_REPROCESS;
	public  int rownum_PRODUCTIONLOSS;
	public  int rownum_EF;
	public  int rownum_PEFL;
	public  int rownum_UEFL;
	public  int rownum_PROCESSFAILURE;
	public  int rownum_EFJ;
	public  int rownum_SETUPANDADJ;
	public  int rownum_TOOLCHANGELOSS;
	public  int rownum_TOOLCHANGSUBJEC;
	public  int rownum_TOOLCHANGEACHIV;
	public  int rownum_TOOLCHANGEBDF;
	public  int rownum_STARTUPLOSS;
	public  int rownum_MS;
	public  int rownum_SPEEDLOSS;
	public  int rownum_SHUTDOWNLOSS;
	public  int rownum_JH;
	public  int rownum_PM;
	public  int rownum_PTRAINING;
	public  int rownum_PMEETING;
	public  int rownum_PELECSHUTDOWN;
	public  int rownum_PGASSHUTDOWN;
	public  int rownum_PAIRSHUTDOWN;
	public  int rownum_OPLANSHUTDOWN;
	public  int rownum_BREAKS;
	public  int rownum_SPARETRIALEXP;
	public  int rownum_RAWTRIALEXP;
	public  int rownum_PROGRAMCANCEL;
	public  int rownum_PROGRAMHELDUP;
	public  int rownum_SPLTRAINING;
	public  int rownum_MANAGEMENTLOSS;
	public  int rownum_WAITINSTRUCTION;
	public  int rownum_WAITMATERIAL;
	public  int rownum_WAITPERSONAL;
	public  int rownum_WAITTUBE;
	public  int rownum_WAITINK;
	public  int rownum_WAITSOLVENT;
	public  int rownum_WAITVIALTRAY;
	public  int rownum_WAITPSPLATE;
	public  int rownum_WAITLASTSHEET;
	public  int rownum_INSPROGCHANGE;
	public  int rownum_WAITSHERSHEET;
	public  int rownum_WAITPARAOIL;
	public  int rownum_WAITCUTTINGOIL;
	public  int rownum_WAITCAPSHELL;
	public  int rownum_WAITWADS;
	public  int rownum_CAPSHELL;
	public  int rownum_WAITPLASTICCAP;
	public  int rownum_WAITSEAL;
	public  int rownum_WAITCOLOURPP;
	public  int rownum_WAITMASTERBASE;
	public  int rownum_WAITPP;
	public  int rownum_COMMONUTILITY;
	public  int rownum_MOTIONLOSS;
	public  int rownum_LINEORGLOSS;
	public  int rownum_LOGISTICSLOSS;
	public  int rownum_MEASUREMENTLOSS;
	public  int rownum_ENERGYLOSS;
	public  int rownum_DIETOOLJIGLOSS;
	public  int rownum_YIELDLOSS;
	public  int rownum_REMARKS;
	public  int rownum_RESULTS;
	public  int rownum_LOADINGTIME;
	public  int rownum_PRODAVLTIME;
	public  int rownum_EFFPRODMINS;
	public  int rownum_ROA;
	public  int rownum_ROP;
	public  int rownum_ROQ;
	public  int rownum_OEE;

	public PCSRownumConstants(List<String[]> dataList, int colnumber ){
		int rowNum =0;
		for( String[] row : dataList){
			
			if( MCHAVLTIME.equals(row[ colnumber ]) )
				rownum_MCHAVLTIME = rowNum; 
		
			rowNum++;				
		}
		
	}
}
