//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.27 at 01:17:32 PM IST 
//


package com.akranta.tpm.upload;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.akranta.tpm.utils.CommonFunctions;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element ref="{}UploadTable"/>
 *         &lt;element ref="{}rules"/>
 *         &lt;element ref="{}validations"/>
 *       &lt;/choice>
 *       &lt;attribute name="auto" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="dateFormat" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="defaultValue" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="excelColHeader" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="excelColIndex" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="insert" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="primaryKey" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="refCol" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="refWhereCol" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="refcol" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="references" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="refwherecol" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="unique" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uploadTable",
    "rules",
    "validations"
})
@XmlRootElement(name = "field")
public class Field {
	
	@XmlTransient
    private Integer ID;
    @XmlTransient
    private Integer uploadTableID;
    @XmlTransient
    private Integer refTableID;
    @XmlTransient
    public static final String seqNoGen ="UPLD_UPLOADFIELD_ID";

    @XmlElement(name = "UploadTable")
    protected UploadTable uploadTable;
    protected Rules rules;
    protected Validations validations;
    @XmlAttribute
    protected Boolean auto;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String dateFormat;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String defaultValue;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String excelColHeader;
    @XmlAttribute(required = true)
    protected Integer excelColIndex;
    
    //private int tmpTblColIndex;
    //private String refKeyid
    
    @XmlAttribute
    protected Boolean refInsert;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlAttribute
    protected Boolean primaryKey;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String refCol;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String refWhereCol;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String references;
    @XmlAttribute
    protected Boolean required;
    @XmlAttribute
    protected Integer size;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String type;
    @XmlAttribute
    protected Boolean unique;
    @XmlAttribute(required = false)
    private Integer tmpTblColIndex; 


	@XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String seqFormat;
    @XmlAttribute(required = true)
    protected Integer seqLength;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String seqPrefix;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String seqReset;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String seqIdentifier;

 /*   @XmlAttribute(required = false)
    protected StringBuilder updateReferenceSql;
  */  
    public Integer getID() {
		return ID;
	}

	public Integer getUploadTableID() {
		return uploadTableID;
	}

	public void setUploadTableID(Integer uploadTableID) {
		this.uploadTableID = uploadTableID;
	}

	public void setRefTableID(Integer refTableID) {
		this.refTableID = refTableID;
	}

	public Integer getRefTableID() {
		return refTableID;
	}

	public void setID(int iD) {
		ID = iD;
	}	
    /**
     * Gets the value of the uploadTable property.
     * 
     * @return
     *     possible object is
     *     {@link UploadTable }
     *     
     */
    
    public UploadTable getUploadTable() {
        return uploadTable;
    }

    /**
     * Sets the value of the uploadTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link UploadTable }
     *     
     */
    public void setUploadTable(UploadTable value) {
        this.uploadTable = value;
    }

    /**
     * Gets the value of the rules property.
     * 
     * @return
     *     possible object is
     *     {@link Rules }
     *     
     */
    public Rules getRules() {
        return rules;
    }

    /**
     * Sets the value of the rules property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rules }
     *     
     */
    public void setRules(Rules value) {
        this.rules = value;
    }

    /**
     * Gets the value of the validations property.
     * 
     * @return
     *     possible object is
     *     {@link Validations }
     *     
     */
    public Validations getValidations() {
        return validations;
    }

    /**
     * Sets the value of the validations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Validations }
     *     
     */
    public void setValidations(Validations value) {
        this.validations = value;
    }

    /**
     * Gets the value of the auto property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAuto() {
        return auto;
    }

    /**
     * Sets the value of the auto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAuto(Boolean value) {
        this.auto = value;
    }

    /**
     * Gets the value of the dateFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateFormat() {
        return dateFormat;
    }

    /**
     * Sets the value of the dateFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateFormat(String value) {
        this.dateFormat = value;
    }

    /**
     * Gets the value of the defaultValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * Sets the value of the defaultValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultValue(String value) {
        this.defaultValue = value;
    }

    /**
     * Gets the value of the excelColHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcelColHeader() {
        return excelColHeader;
    }

    /**
     * Sets the value of the excelColHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcelColHeader(String value) {
        this.excelColHeader = value;
    }

    /**
     * Gets the value of the excelColIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExcelColIndex() {
        return excelColIndex;
    }

    /**
     * Sets the value of the excelColIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExcelColIndex(Integer value) {
        this.excelColIndex = value;
    }

    /**
     * Gets the value of the insert property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRefInsert() {
        return refInsert;
    }

    /**
     * Sets the value of the insert property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRefInsert(Boolean value) {
        this.refInsert = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the primaryKey property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrimaryKey() {
        return primaryKey;
    }

    /**
     * Sets the value of the primaryKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrimaryKey(Boolean value) {
        this.primaryKey = value;
    }

    /**
     * Gets the value of the refCol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefCol() {
        return refCol;
    }

    /**
     * Sets the value of the refCol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefCol(String value) {
        this.refCol = value;
    }

    /**
     * Gets the value of the refWhereCol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefWhereCol() {
        return refWhereCol;
    }

    /**
     * Sets the value of the refWhereCol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefWhereCol(String value) {
        this.refWhereCol = value;
    }

    
    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferences(String value) {
        this.references = value;
    }

     /**
     * Gets the value of the required property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequired(Boolean value) {
        this.required = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSize(Integer value) {
        this.size = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the unique property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUnique() {
        return unique;
    }

    /**
     * Sets the value of the unique property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUnique(Boolean value) {
        this.unique = value;
    }

    public void setTmpTblColIndex(Integer tmpTblColIndex){
    	this.tmpTblColIndex = tmpTblColIndex;
    	
    }
    
    public Integer getTmpTblColIndex(){
    	return this.tmpTblColIndex ;
    	
    }
    
    public String getSeqFormat() {
		return seqFormat;
	}

	public void setSeqFormat(String seqFormat) {
		this.seqFormat = seqFormat;
	}

	public Integer getSeqLength() {
		return seqLength;
	}

	public void setSeqLength(Integer seqLength) {
		this.seqLength = seqLength;
	}

	public String getSeqPrefix() {
		return seqPrefix;
	}

	public void setSeqPrefix(String seqPrefix) {
		this.seqPrefix = seqPrefix;
	}

	public String getSeqReset() {
		return seqReset;
	}

	public void setSeqReset(String seqReset) {
		this.seqReset = seqReset;
	}

	public String getSeqIdentifier() {
		return seqIdentifier;
	}

	public void setSeqIdentifier(String seqIdentifier) {
		this.seqIdentifier = seqIdentifier;
	}

	 @XmlTransient
	 public String getInsertSql(){
		CommonFunctions.debugMsg(" this.name "  +  this.name  +  "  ID "  +  this.ID ); 
    	StringBuilder sql = new StringBuilder();
    	sql.append(" insert into UPLOADTBLFIELDS (ID,uploadTableID,refTableID,name,excelColHeader,excelColIndex,required,"); 
    	sql.append(" defaultValue,type,datasize, dateFormat,references,refCol,refWhereCol,refInsert,auto,primaryKey,uniquefld,seqPrefix,seqFormat,seqReset,seqIdentifier,seqLength) values (");
    	sql.append(this.ID  +  ","  +  this.uploadTableID  +  ","  +  (this.refTableID == null ? 0:this.refTableID )  +  ",'"  +  this.name  +  "','"  +  (this.excelColHeader == null ?  "" :this.excelColHeader )  +  "',"  +  this.excelColIndex  +  ",'"  +  ( this.required == null || this.required == false ? "N" : "Y" ) + "'," ); 
    	sql.append("'"  +  (this.defaultValue == null ? "" : this.defaultValue )  +  "','"  +  this.type  +  "','"  +  this.size  +  "','"  +  (this.dateFormat == null?"":this.dateFormat)  +  "','"  +  (this.references == null? "" : this.references)  +  "','"  +  (this.refCol == null ? "" : this.refCol)  +  "'," );
    	sql.append("'"  +  (this.refWhereCol == null ? "":this.refWhereCol)  +  "','"  +  (this.refInsert != null && this.refInsert ? "Y":"N")  +  "','"  +  (this.auto != null && this.auto ?"Y":"N")  +  "',"  );
    	sql.append("'"  +  (this.primaryKey != null && this.primaryKey ? "Y":"N")  +  "','"  +  (this.unique != null && this.unique ? "Y":"N")  +  "',"  );		  
    	sql.append("'"  +  (this.seqPrefix ==null ? "":this.seqPrefix)  +  "','"  + (this.seqFormat == null?"":this.seqFormat)  +  "','"  +  (this.seqReset==null?"":this.seqReset) +  "','"  +  (this.seqIdentifier==null?"":this.seqIdentifier)  +  "',"  + this.seqLength  +  ")" );
    	return sql.toString();
	 }
	 @XmlTransient
	 public String getUpdateSql(){
    	String sql = " update  UPLOADTBLFIELDS set (ID,uploadTableID,refTableID,name,excelColHeader,excelColIndex,required,"  + 
    			"defaultValue,type,datasize, dateFormat,references,refCol,refWhereCol,refInsert,auto,primaryKey,uniquefld,seqPrefix,seqFormat,seqReset,seqIdentifier,seqLength) values";
    	sql  +=  "("  + this.ID  +  ","  +  this.uploadTableID  +  ","  +  this.refTableID  +  ",'"  + this.name  +  "','"  +  this.excelColHeader  +  "','"  + this.excelColIndex  +  "','"  +  this.required != null && this.required ? "Y" :"N"  + 
    		    "','"  +  this.defaultValue  +  "','"  +  this.type  +  "','"  +  this.size  +  "','"  +  this.dateFormat  +  "','"  +  this.references  +  "','"  +  this.refCol  +  "',"  + 
    		    "'"  +  this.refWhereCol  +  "','"  +  this.refInsert != null && this.refInsert ? "Y":"N"  +  "','"  +  this.auto != null && this.auto ?"Y":"N"  +  "',"  + 
    		    "'"  +  this.primaryKey != null && this.primaryKey ? "Y":"N"  +  "','"  +  this.unique != null && this.unique ? "Y":"N"  +  "',"  + 		  
    		    "'"  +  this.seqPrefix  +  "','"  + this.seqFormat  +  "','"  + this.seqReset +  "','"  + this.seqIdentifier +  "',"  + this.seqLength  +  ")";
    	return sql;
	 }
}
