//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.27 at 01:17:32 PM IST 
//
package com.akranta.tpm.upload;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}field" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="seqCol" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="seqFormat" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="seqLength" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="seqPrefix" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="seqReset" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "field"
})
@XmlRootElement(name = "UploadTable")
public class UploadTable {

	@XmlTransient
    private Integer ID = null;
    @XmlTransient
    private Integer uploadDataID = null;
    @XmlTransient
    public static final String seqNoGen ="UPLD_UPLOADTABLE_ID";
    
	@XmlElement(required = true)
    protected List<Field> field;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String seqCol;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String seqFormat;
    @XmlAttribute(required = true)
    protected Integer seqLength;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String seqPrefix;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String seqReset;

  /*  @XmlAttribute(required = false)
    protected StringBuilder insertSql;
    @XmlAttribute(required = false)
    protected StringBuilder updateSql;
   */
    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * 
     * 
     */
    public List<Field> getField() {
        if (field == null) {
            field = new ArrayList<Field>();
        }
        return this.field;
    }

    public Integer getID() {
		return ID;
	}

	public Integer getUploadDataID() {
		return uploadDataID;
	}

	public void setUploadDataID(Integer uploadDataID) {
		this.uploadDataID = uploadDataID;
	}

	public void setID(Integer iD) {
		ID = iD;
	}
	
    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the seqCol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeqCol() {
        return seqCol;
    }

    /**
     * Sets the value of the seqCol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeqCol(String value) {
        this.seqCol = value;
    }

    /**
     * Gets the value of the seqFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeqFormat() {
        return seqFormat;
    }

    /**
     * Sets the value of the seqFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeqFormat(String value) {
        this.seqFormat = value;
    }

    /**
     * Gets the value of the seqLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSeqLength() {
        return seqLength;
    }

    /**
     * Sets the value of the seqLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSeqLength(Integer value) {
        this.seqLength = value;
    }

    /**
     * Gets the value of the seqPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeqPrefix() {
        return seqPrefix;
    }

    /**
     * Sets the value of the seqPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeqPrefix(String value) {
        this.seqPrefix = value;
    }

    /**
     * Gets the value of the seqReset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeqReset() {
        return seqReset;
    }

    /**
     * Sets the value of the seqReset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeqReset(String value) {
        this.seqReset = value;
    }

    @XmlTransient
    public String getInsertSql(){
    	String sql = " insert into UPLOADTABLE (ID,uploadDataID,name,seqCol,seqPrefix,seqFormat,seqReset,seqLength) values";
    	sql += "("+this.ID +","+ this.uploadDataID +",'" +this.name +"','"+ (this.seqCol ==  null ?"":this.seqCol) + "','" + (this.seqPrefix==null ? "":this.seqPrefix) +"','"+(this.seqFormat==null?"":this.seqFormat) +"','" + (this.seqReset==null?"":this.seqFormat) +"',"+this.seqLength +")";
    	return sql;
    }

    @XmlTransient
    public String getUpdateSql(){
    	String sql = " update UPLOADTABLE (ID,uploadDataID,name,seqCol,seqPrefix,seqFormat,seqReset,seqLength) values";
    	sql += "("+this.ID +","+ this.uploadDataID +",'" +this.name +"','"+this.seqCol +"','"+this.seqPrefix +"','"+this.seqFormat +"','"+this.seqReset+"',"+this.seqLength +")";
    	return sql;
    }
}
