//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.27 at 01:17:32 PM IST 
//


package com.akranta.tpm.upload;

import java.math.BigInteger;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}UploadTable"/>
 *       &lt;/sequence>
 *       &lt;attribute name="file" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="format" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="maxRecords" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="sheet" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="startFromRow" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="totalFields" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uploadTable"
})
@XmlRootElement(name = "uploadData")
public class UploadData {

    @XmlTransient
    private Integer ID=null;
    @XmlTransient
    public static final String seqNoGen ="UPLD_UPLOADDATA_ID"; 
	@XmlElement(name = "UploadTable", required = true)
    protected List<UploadTable> uploadTable;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String file;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String format;
    @XmlAttribute(required = true)
    protected Integer maxRecords;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sheet;
    @XmlAttribute(required = true)
    protected Integer startFromRow;
    @XmlAttribute(required = true)
    protected Integer totalFields;

    
    
    public Integer getID() {
		return ID;
	}

	public void setID(Integer iD) {
		ID = iD;
	}

	/**
     * Gets the value of the uploadTable property.
     * 
     * @return
     *     possible object is
     *     {@link UploadTable }
     *     
     */
    public List<UploadTable> getUploadTable() {
        return uploadTable;
    }

    /**
     * Sets the value of the uploadTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link UploadTable }
     *     
     */
    public void setUploadTable(List<UploadTable> value) {
        this.uploadTable = value;
    }

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFile(String value) {
        this.file = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the maxRecords property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxRecords() {
        return maxRecords;
    }

    /**
     * Sets the value of the maxRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxRecords(Integer value) {
        this.maxRecords = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the sheet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSheet() {
        return sheet;
    }

    /**
     * Sets the value of the sheet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSheet(String value) {
        this.sheet = value;
    }

    /**
     * Gets the value of the startFromRow property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStartFromRow() {
        return startFromRow;
    }

    /**
     * Sets the value of the startFromRow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStartFromRow(Integer value) {
        this.startFromRow = value;
    }

    /**
     * Gets the value of the totalFields property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalFields() {
        return totalFields;
    }

    /**
     * Sets the value of the totalFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalFields(Integer value) {
        this.totalFields = value;
    }

    @XmlTransient
    public String getCreateStatement(){
    	return " ";
    }
    @XmlTransient
    public String getInsertSql(){
    	String sql = " insert into UPLOADDATA (ID,name,filename,format,sheet,maxrecords,totalfields,startfromrow) values";
    	sql += "("+this.ID +",'" +this.name +"','"+this.file +"','"+this.format +"','"+this.sheet +"',"+this.maxRecords +","+this.totalFields+","+this.startFromRow +")";
    	return sql;
    }
    @XmlTransient
    public String getUpdateSql(){
    	String sql = " Update UPLOADDATA set name='" +this.name +"',filename='"+this.file +"',";
    	sql +=   "format='"+ this.format+ "',sheet='"+this.sheet +"',"+
    	        "maxRecords="+this.maxRecords +",totalFields="+this.totalFields+
    	        ",startFrom="+this.startFromRow +" where ID="+this.ID;
    	return sql;
    }
}
