ApldActionplan-required=["txtApldActionplan","Enter Action Plan"]
ApldTradeid-required=["cmbApldTradeid","Select Trade"]
ApldResponsibility-required=["cmbApldResponsibility","Select Responsibility"]
ApldCompletedby-required=["cmbApldCompletedby","Select Completed By"]
ApldCompleatedon-required=["dteApldCompleatedon","Select Completed Date"]
UK_ACTIONPLANDTL=["Duplicate Entry"]