LDAP_SERVER_URL= ldap://PSPDBCMDC001:389
LDAP_SERVER_URL= ldap://server:389
#LOTUS_NOTES_SERVER_NAME=KOLMAIL01/ITC
#LOTUS_NOTES_SERVER_NAME=

#LOTUS_NOTES_DB_FILENAME=pspdmailnew\PERFEX
#LOTUS_NOTES_DB_FILENAME=names.nsf
#LOTUS_NOTES_USERNAME=PERFEX 360/PSPD/ITC
#LOTUS_NOTES_PASSWORD=ospoexeD=9


COMBO_FETCH_RECORDS=100
#SMTP_HOST=smtp.gmail.com
#SMTP_PORT=465
#SMTP_USER_NAME=info.akranta@gmail.com
#SMTP_USER_PWD=
#SMTP_FROM_ADDRESS=info.akranta@gmail.com

#SMTP_HOST=10.18.1.7
#SMTP_FROMADDRESS=pspd.perfex@itc.in
#SMTP_PWD=
#SMTP_PORT=25
#

SMTP_HOST=smtp.rediffmailpro.com
SMTP_FROMADDRESS=kiran@akranta.in
SMTP_PWD=Kiran@1987
SMTP_PORT=465

#SMTP_HOST=smtp.gmail.com
#SMTP_FROMADDRESS=vamtec25@gmail.com
#SMTP_PWD=lgvp sjgm crwq wgml
#SMTP_PORT=587

#OSMTM_HOST=smtp.rediffmailpro.com
#OSMTM_FROMADDRESS=kiran@akranta.in
#OSMTM_PWD=Kiran@1987
#OSMTM_PORT=465

#OSMTM_HOST=10.19.1.72
#OSMTM_FROMADDRESS=pspd.perfex@itc.in
#OSMTM_PWD=
#OSMTM_PORT=25

#OSMTM_FROMADDRESS=PSPD.APPSupport@itc.in
#OSMTM_PORT=25
#OSMTM_FROMADDRESS=PSPD.APPSupport@itc.in
#OSMTM_PORT=25

#OSMTM_HOST=10.19.1.72
#OSMTM_FROMADDRESS=PSPD.APPSupport@itc.in
#OSMTM_PORT=25



SCHDULER_ENABLE=YES
SCHDULER_LOCATION=bcm-pspd

SCHDULER_ENVIRONMENT=QUALITY
CRM_SOURCEPATH=C:\\Users\\Administrator\\Downloads\\CRM
LDAP_SERVER_DOMAIN=ITC
FILEMANGER_BASE_PATH=Z:/PerfexFiles
LOG_REQUIRE=Y
URL_LOG_REQUIRE=Y
CON_LOG_REQUIRE=Y

BASE_URL=http://localhost:9090/api
