AppsName-required=["txtAppsName","Enter Name"]
AppsCode-required=["txtAppsCode","Enter Code"]
AppsSettingvalue-required=["txtAppsSettingvalue","Enter Setting Value"]
AppsType-required=["txtAppsType","Enter Type"]
AppsTransactionmode-required=["txtAppsTransactionmode","Enter Mode"]
AppsOrder-required=["txtAppsOrder","Enter Order"]
AppsPillar-required=["txtAppsPillar","Enter Pillar"]



