GmntFactoryid-required=["cmbGmntFactoryid","Enter Factory"]
GmntSectionid-required=["cmbGmntSectionid","Select Section"]
GmntLineid-required=["cmbGmntLineid","Select Cell"]
GmntMachineid-required=["cmbGmntMachineid","Enter Machine"]
GmntRelatedto-required=["cmbGmntRelatedto","Select Related To"]
GmntShiftdate-required=["dteGmntShiftdate","Select Shift Date"]
GmntShiftdate-EQUAL=["dteGmntShiftdate","Shift Date Should<br> be Equal to Occured Date<br>"]
GmntShift-required=["cmbGmntShift","Select Shift"]
GmntTrade-required=["cmbGmntTrade","Select Maintenance section"]
GmntOccureddate-required=["dteGmntOccureddate","Select Occured Date"]
GmntOccureddate-EQUAL=["dteGmntOccureddate","Occured Date Should be Equal to Shift Date"]
GmntActivitytype-required=["cmbGmntActivitytype","Select Activity type"]
GmntProblem-required=["txtGmntProblem","Enter Problem"]
GmntTargetdate-LE=["dteGmntTargetdate","<span>Target Date Should Be</span><br> Greater or Equal to Occured Date"]
GmntReportedby-required=["cmbGmntReportedby","Select Reported By"]
GmntStatus-required=["cmbGmntStatus","Select Status"]
GmntCompletedby-required=["cmbGmntCompletedby","Select Completed By"]
GmntWostartdate-required=["dteGmntWostartdate","Select Work Start Date"]
GmntWostartdate-LE=["dteGmntOccureddate","WorkStartDate must be Greater or Equal to Occured Date"]
GmntWoenddate-required=["dteGmntWoenddate","Select Work End Date"]
GmntWoenddate-LE=["dteGmntWoenddate","Work End Date must be Greater or Equal to Work Start Date"]
GmntWoenddate-LECD=["dteGmntWoenddate","Work End date should be lesser or equal to current date"]
GmntMouldid-required=["cmbGmntMouldid","Select Mould Id"]
GmntAction-required=["txtGmntAction","Enter Action"]
lossDuration=["Loss Duration Should be Equal to Downtime"]
MAXCOMPDATE=["Maximum 5 days from occured date to be completed"]
msrOverlap=["MSR Overlap"]