
#Emp Cost
MpcpSkillid-required=["cmbmpcpSkillid","Select Grade"]
MpcpManpowerid-required=["cmbmpcpManpowerid","Select Employee"]
MpcpNormalmins-required=["txtmpcpNormalmins","Enter Minutes"]
MpcpNormalcost-required=["txtmpcpNormalcost","Enter Cost"]
UK_MPCP_WOIDMANSKILL=["Same Record Already Exist"]

MpcsSkillid-required=["cmbmpcsSkillid","Select Grade"]
MpcsManpowerid-required=["cmbmpcsManpowerid","Select Employee"]
MpcsDate-required=["dtempcsDate","Enter Date"]
MpcsNormalwt-required=["txtmpcsNormalwt","Nor Mins"]
MpcsHolidaywt-required=["txtmpcsHolidaywt","Call-Out"]
MpcsOtherwt-required=["txtmpcsOtherwt","OT-Mins"]
MpcsActivity-required=["txampcsActivity","Enter Activity"]
UK_MPCS_WOIDMANSKILL=["Same Record Already Exist"]
MpcsDate-LE=["dteworkStart","Date Should not be lesser than Work Start Date "]
MpcsDate-GE=["dteworkEnd","Date Should not be greater than Work End Date "]

#Spare Cost
WscpRequestedby-required=["cmbwscpRequestedby","Select Requested By"]
WscpSparesid-required=["cmbwscpSparesid","Select Spares"]
WscpQuantity-required=["txtwscpQuantity","Enter Qty"]
UK_WSCP_WOIDSPAREREQ=["Same Record Already Exist"]

WscaRequestedby-required=["cmbwscaRequestedby","Select Requested By"]
WscaSparesid-required=["cmbwscaSparesid","Select Spares"]
WscaQuantity-required=["txtwscaQuantity","Enter Qty"]
UK_WSCA_WOIDSPAREREQ=["Same Record Already Exist"]

#Service Cost
SvcpServiceid-required=["cmbsvcpServiceid","Select Service"]
SvcpJobdescription-required=["txasvcpJobdescription","Enter Job Description"]
SvcpBillvalue-required=["txtsvcpBillvalue","Enter Bill Value"]
UK_SVCP_WOIDSER=["Same Record Already Exist"]

SvcaServiceid-required=["cmbsvcaServiceid","Select Service"]
SvcaJobdescription-required=["txasvcaJobdescription","Enter Job Description"]
SvcaBilldate-required=["dtesvcaBilldate","Select Bill Date"]
SvcaBillvalue-required=["txtsvcaBillvalue","Enter Bill Value"]
UK_SVCA_WOIDSER=["Same Record Already Exist"]

#Utility Cost
UtcpUtilitymstid-required=["cmbutcpUtilitymstid","Select Utility"]
UtcpRequestedby-required=["cmbutcpRequestedby","Select Requested By"]
UtcpQuantity-required=["txtutcpQuantity","Enter Qty."]
UtcpMinutes-required=["txtutcpMinutes","Enter Min."]
UK_UTCP_WOIDUTIREQ=["Same Record Already Exist"]

UtcaUtilitymstid-required=["cmbutcaUtilitymstid","Select Utility"]
UtcaRequestedby-required=["cmbutcaRequestedby","Select Requested By"]
UtcaQuantity-required=["txtutcaQuantity","Enter Qty."]
UtcaMinutes-required=["txtutcaMinutes","Enter Min."]
UtcaDate-required=["dteutcaDate","Select Date"]
UK_UTCA_WOIDUTIREQ=["Same Record Already Exist"]

#Other Cost
OtcpOthercostmstid-required=["cmbotcpOthercostmstid","Select Other"]
OtcpRequestedby-required=["cmbotcpRequestedby","Select Requested By"]
OtcpAmount-required=["txtotcpAmount","Enter Amount"]
UK_OTCP_WOIDOTHREQ=["Same Record Already Exist"]

OtcdOthercostmstid-required=["cmbotcdOthercostmstid","Select Expense"]
OtcdRequestedby-required=["cmbotcdRequestedby","Select Requested By"]
OtcdAmount-required=["txtotcdAmount","Enter Cost"]
OtcdDate-required=["dteotcdDate","Select Date"]
UK_OTCD_WOIDOTHREQ=["Same Record Already Exist"]