BdmsRelatedto-required=["cmbbdmsRelatedto","Select Related To"]
BdmsFactoryid-required=["cmbbdmsFactoryid","Select Unit"]
BdmsSectionid-required=["cmbbdmsSectionid","Select Sub Unit"]
BdmsCellid-required=["cmbbdmsCellid","Select Section"]
BdmsMachineid-required=["cmbbdmsMachineid","Select Equipment"]
BdmsMould-required=["cmbbdmsMould","Select Mould"]
BdmsReporteddate-required=["dtebdmsReporteddate","Select Occured Date"]
BdmsPriority-required=["cmbbdmsPriority","Select Priority"]
BdmsAssemblyid-required=["cmbbdmsAssemblyid","Select Assembly"]
BdmsFinalphenomena-required=["cmbbdmsFinalphenomena","Select Phenomena"]
BdmsBookedby-required=["cmbbdmsBookedby","Select Booked By"]
BdmsShiftid-required=["cmbbdmsShiftid","Select Shift Id"]
BdmsBookedtrade-required=["cmbbdmsBookedtrade","Select Maint. Section"]
BdmsActualworktime-required=["dtebdmsWostarttime","Enter Work Start & End Details"]
#BdanCostcentre-required=["cmbbdanCostcentre","Select Cost Center"]
ExtmMaterialGroup-required=["cmbExtmMaterialGroup","Select Material Group"]
ExtmPurchaseGroup-required=["cmbExtmPurchaseGroup","Select Purchase Group"]
ExtmVendor-required=["cmbExtmVendor","Select Vendor"]
ExtmRequisitioner-required=["cmbExtmRequisitioner","Select Requisitioner"]
ExtmPurchaseOrg-required=["cmbExtmPurchaseOrg","Select Purchase Organization"]
BdanFailuretype-required=["cmbbdanFailuretype","Select Failure Type"]
BdanClassificationid-required=["cmbbdanClassificationid","Select Classification"]
BdanCompletedby-required=["cmbbdanCompletedby","Select Analysed By"]
Woendtime-required=["chbWoendtime"]
BdmsWostarttime-LE=["dtebdmsWostarttime","Work Start should be lesser than Production Acceptance Date"]
BdmsWostarttime-LECD=["dtebdmsWostarttime","Select Work Start Time"]
BdmsWoendtime-LE=["dtebdmsWoendtime","Work End should be lesser than Production Acceptance Date"]
BdmsReceiveddate-LECD=["dtebdmsReceiveddate","Select Received Date"]
BdmsWostartflag-required=["chbbdmsWostartflag","Select Work Start Time"]
BdmsWoendflag-required=["chbbdmsWoendflag","Select Work End Time"]
UndefinedPhen=["This BD has Undefined Phenomena.Do You want to raise the proposal?"] 
MAXCOMPDATE=["COMPLETED DATE EXCEEDS THE LIMIT"]
msrOverlap=["MSR Overlap"]
prodAccept=["Production Accepted.Cannot be delete."]