CellName-required=["txtCellName","Enter Name"]
CellCode-required=["txtCellCode","Enter Code"]
CellCostcentreid-required=["cmbCellCostcentreid","Select Cost Center"]
UK_CELL_NAME=["Name is Already Exist"]
UK_CELL_CODE=["Code is Already Exist"]
