CucmComplaintno-required=["err_txtcucmComplaintno","Select Complaint No."]
CucmBatchno-required=["err_txtcucmBatchno","Enter Batch No."]
CucmDcno-required=["err_txtcucmDcno","Enter DC No."]
CucdCustomerid-required=["cmbcucdCustomerid","Select Customer"]
CucdProductid-required=["cmbcucdProductid","Select Product"]
CucdComplaintdescription-required=["txtcucdComplaintdescription","Enter Customer Complaint Description"]
CucdComplainttype-required=["cbocucdComplainttype","Select Customer Complaint Type"]
CucdSpecification-required=["txtcucdSpecification","Enter Customer Specification"]
CucdRecordedby-required=["cmbcucdRecordedby","Select Recorded By"]
CucdTotalqtydespatch-required=["txtcucdTotalqtydespatch","Enter Total Qty Despd"]
CucdTotaldefectdesp-required=["err_txtcucdTotaldefectdesp","Enter Defect Despd"]
CucdClosedon-LECD=["dtecucdClosedon","Closed On Date cannot be greater then current Date"]
CucmComplaintdate-LE=["dtecucmComplaintdate","Complaint Date must be Greater or Equal to Produced Date"]
CucmDcdate-LE=["dtecucmDcdate","DC Date must be Greater or Equal to Complaint Date"]
CucmManufactureddate-LE=["dtecucmManufactureddate","Manufactured Date must be Greater or Equal to Produced Date"]
CucmManufactureddate-GE=["dtecucmManufactureddate","Manufactured Date must be less than or Equal to Complaint Date"]
CucmCellid-required=["cmbcucmCellid","Select Cell"]