Type=[{"id":"P","text":"Pending"},{"id":"C","text":"Completed"}]
Aspect=[{"id":"W","text":"Work Permit System"},{"id":"H","text":"Housekeeping & Hygiene"},{"id":"P","text":"Storage Practices"},{"id":"E","text":"Electricals"},{"id":"S","text":"Service Provider`s Safety"},{"id":"O","text":"Others"}]
