EhsTemplatename-required=["txtEhsTemplatename","Enter Name"]
EhsTemplatecode-required=["txtEhsTemplatecode","Enter Code"]
EhsAudittype-required=["cmbEhsAudittype","Select Audit Type"]
EhsAuditlevel-required=["cmbEhsAuditlevel","Select Audit Level"]
EhsRevisionno-required=["txtEhsRevisionno","Enter Revision No"]
EhsRevisiondate-required=["dteEhsRevisiondate","Select Date"]
EhsRevisiondate-LECD=["dteEhsRevisiondate","Revision Date Should Be Less Than Or Equal To Current Date"]
UK_EHS_TL_AUDITPARAMETER=["This Template Already Exists"]
FK_EHSM_AUDITTEAMID =["Data have been referred"]
FK_EHSAD_PARAMETERID =["This Parameter have been referred"]