NommProgKeyid-required=["cmbNommProgKeyid","Select Program"]
NommBachKeyid-required=["cmbNommBachKeyid","Select Batch"]
NommPreparedBy-required=["cmbNommPreparedBy","Select Prepared By"]
NommPreparedDate-required=["dteRasmDate","Enter Prepared Date"]
NommPreparedDate-LECD=["dteNommPreparedDate","Prepared Date Should Be Less Than Or Equal To Current Date"]