ErdlFactKeyid-required=["hdnerdlFactKeyid",""]
ErdlDeptKeyid-required=["cmberdlDeptKeyid","Select Department"]
ErdlCellFunKeyid-required=["","Select Cell/Function"]
ErdlRoleKeyid-required=["cmberdlRoleKeyid","Select Role"]
#ErdlElectiveSkills-required=["txterdlElectiveSkills","Enter Elective Skills"]
ErslSkillKeyid-required=["cmberslSkillKeyid","Enter Work Order No"]
ErslMandatoryType-required=["cmbErslMandatoryType","Select Mandtory Type"]
ErslTargetRating-required=["cmberslTargetRating","Select Target Ratting"]
ErslRatingType-required=["cmberslRatingType","Select Ratting Type"]
ErelEmpmKeyid-required=["cmberelEmpmKeyid","Select Employee"]
UK_ERDL_EMPM_ID=["Employee Name Already Exists"]
UK_EREL_RTAL_EMPM_KEYID=["Employee Name Already Exists"]
#view_Mode=["Data cannot be saved in view mode"]
