BsdlBachKeyid-required=["","Select Batch"]
BsdlProgKeyid-required=["","Select Program"]
BsdlScheduleDate-required=["","Select Schedule Date"]
BsdlFromtime-required=["","Select From Time"]
BsdlTilltime-required=["","Select Till Time"]
FK_BSDL_PROG_KEYID=["Check Program Calendar"]
#view_Mode=["Data cannot be saved in view mode"]
