ProgName-required=["txtProgName","Enter Program Name"]
#ProgKeyid-required=["cmbProgKeyid","Select Program "]
ProgCode-required=["cmbProgCode","Select Topic"]
#ProgUniquepos-required=["cmbProgUniquepos","Select Unique Position "]
ProgMonth-required=["dteProgMonth","Select Month "]
#ProgCode-required=["txtProgCode","Enter Program Code"]
#ProgSpokeKeyid-required=["cmbProgSpokeKeyid","Select Spoke"]
ProgType-required=["cmbProgType","Enter Skill Type"]
ProgMinDuration-required=["txtProgMinDuration","Enter Minimum Duration"]
ProgMaxDuration-required=["txtProgMaxDuration","Enter Maximum Duration"]
#ProgMinDuration-GE=["txtProgMinDuration","Maximum Duration Must Be Greater than Minimum Duration"]
ProgTrarKeyid-required=["trtProgTrarKeyid","Select Location"]
ProgIsEvaluationNeed-required=["chbProgIsEvaluationNeed","Select Evaluation"]
ProgEffectiveFrom-required=["dteProgEffectiveFrom","Select Effective Date"]
BachVenuKeyid-required=["cmbBachVenuKeyid","Select Venu"]
#ProgTgtmKeyid-required=["cmbProgTgtmKeyid","Select Target Group"]
