TrarName-required=["txtTrarName","Enter Name"]
TrarReftype-required=["cmbTrarReftype","Select Reference Type"]
TrarLocationid-required=["cmbTrarLocationid","Select Location"]
#FK_ERSL_SKIL_KEYID=["This RECORD Is Being Referred"]
#FK_ERSR_SKIL_KEYID=["This RECORD Is Being Referred"]
ENT_TL_TRAININGAREA_UK=["This Topic Already Added For This Parent"]
#FK_PRTS_SKIL_KEYID=["This RECORD Is Being Referred"]
