
PeqsAssemblyid-required=["cmbPeqsAssemblyid","Select AssemblyId"]
PeqsSource-required=["chkPeqsSource","select Internal/External"]
PeqsTradeid-required=["cmbPeqsTradeid","Select Maintenance Section"]
PeqsActivitytype-required=["cmbPeqsActivitytype","Select ActivityType"]
PeqsMachinecond-required=["cmbPeqsMachinecond","Select Machine Condition"]
PeqsDuration-required=["txtPeqsDuration","Enter Duration"]
PeqsActivity-required=["txtPeqsActivity","Enter Activity"]
PeqsHowmethod-required=["txtPeqsHowmethod","Enter Method"]
PeqsPreparedbyid-required=["cmbPeqsPreparedbyid","Select Prepared By"]
			
			
			
		    