Section-required=["cmbSection","Select Section"]
MchmCellid-required=["cmbMchmCellid","Select Cell"]
MchmCostcentreid-required=["cmbMchmCostcentreid","Select CostCenter"]
MchmEquipmentgroup-required=["cmbMchmEquipmentgroup","Select Equipment Group"]
MchmMachineno-required=["txtMchmMachineno","Enter Equipment No"]
MchmMachinename-required=["txtMchmMachinename","Enter Machine Name"]
#MchmWorkcenter-required=["cmbMchmWorkcenter","Select Work Center"]
MchmInstalleddate-required=["dteMchmInstalleddate","Enter Install Date"]
MchmEffectivedate-required=["dteMchmEffectivedate","Enter Effective Date"]
MchmMfrslno-required=["txtMchmMfrslno","Enter Mfr SlNo"]
FK_MCEM_MACHINEID=["This RECORD Is Being Referred"]
UK_MACHINENO=["Equipment Number Already Exists"]

#--------------------------Date Validation-------------------
#MchmJhstepdate-LE=["dteMchmJhstepdate","JH Date should  not be less than Effective date"]
MchmManufactureddate-GE=["dteMchmManufactureddate","Manufacture Date should be less than Effective date"]
MchmAmcdate-GE=["dteMchmAmcdate","Renewal Date should  not be less than Contract date"]
MchmWarrantydate-GE=["dteMchmAmcdate","Contract Date should not be less than Warranty date"]
MchmAmcrenewaldate-LE=["dteMchmInstalleddate","Renewal Date should be less than Warranty date"]
#section-required=["cmbsection","Select Section"]
MchmJhstepdate-LE=["dteMchmJhstepdate","JH Date should  not be less than Effective date"]
MchmEffectivedate-LE=["dteMchmEffectivedate","Effective Date Should be Greater than Install Date"]