
required-company=["cmbFunctLocComp","Select Company"]
required-location=["cmbFunctLocLocn","Select Location"]
required-sbu=["cmbFunctLocSBU","Select SBU"]
required-factory=["cmbFunctLocFact","Select Factory"]
required-section=["cmbFunctLocSect","Select DMT"]
required-cell=["cmbFunctLocCell","Select JH"]
required-machine=["cmbFunctLocMachine","Select Equipment"]
