funcnLocn=["#node_1", "#CMP_01","#LCN_01"]
checkBdForMachine=BreakDown Analysis is Incomplete!Moving this Equipment will make them Inactive.Do You Want to continue?
bdList=Moving this Machine will affect the following:
proceed=Do You Want to Proceed?
Move-Confirm=Are You Sure in Moving the Machine?