equipmentGroup_input.eqg=selectEquipmentGroup-false
emp_input.emp=selectEmployee-false-GEN_TL_EMPLOYEEMST
Utility_input.uty=selectUtility-false-GEN_TL_TOOLSMST
Tools_input.uty=selectTools-false-GEN_TL_TOOLSMST
cell_input.cell=selectCell-false-GEN_TL_CELLMST
SBU_input.funlocn=selectSbu-false-GEN_TL_SBUMST
PBU_input.funlocn=selectPbu-false-GEN_TL_PBUMST
section_input.sect=selectSection-false-GEN_TL_SECTIONMST
shift_input.sftm=selectShift-false-GEN_TL_SHIFTMST
company_input.comp=selectCompany-false-GEN_TL_COMPANYMST
assembly_input.asb=selectAssembly-false-GEN_TL_ASSEMBLYMST
factory_input.fact=selectFactory-false-GEN_TL_FACTORYMST
location_input.locn=selectLocation-false-GEN_TL_LOCATIONMST
EmployeeCost_input.ec=selectEmployeeCost-false-GEN_TL_EMPLOYEECOST
UtilityCost_input.ec=selectUtilityCost-false-GEN_TL_TOOLSMST
ContractorCost_input.ec=selectContractorCost-false-WOM_TL_CONTRACTORMST
SkillCheckList_input.checkList=selectCheckListMainGrid-false-ENT_TL_CHECKLISTMST
genTlCircleMst_input.circleMst=selectCircle-false-GEN_TL_CIRCLEMST
TopicEntryMaster_input.topmst=selectTopic-false-ENT_TL_TOPICMST
MessageDashBoard_input.dashboard=selectMessageBoard-false-GEN_TL_MESSAGEBOARD\t
CTQ_input.qams=selectCtq-false-QTM_TL_KPIVMST
sapFl_input.sapinfo=selectSapFunctionalLoc-false-SAP_FUNCTIONAL_LOCN
sapEqp_input.sapinfo=selectSapEqpMaster-false-SAP_EQUIPMENT_MST
sapDowntimeArea_input.sapinfo=selectSapDowntimeAreamst-false-SAP_DOWNTIME_AREA_MST
sapDowntimeReason_input.sapinfo=selectSapDowntimeReason-false-SAP_DOWNTIME_REASONS
sapCostcenter_input.sapinfo=selectSapCostcentermst-false-SAP_COSTCENTER
sapWorkcenter_input.sapinfo=selectSapWorkcenter-false-SAP_WORKCENTER
sapVendormas_input.sapinfo=selectSapVendorMaster-false-GEN_TL_PARTNORMST
sapCustomermas_input.sapinfo=selectSapCustomerMaster-false-SAP_TL_PARTNORMST
sapServicecenter_input.sapinfo=selectSapServiceCenter-false-SAP_TL_SERVICEMST
sapWBSelement_input.sapinfo=selectSapWBSElement-false-SAP_WBS_ELEMENT
sapEquipmentBOM_input.sapinfo=selectSapEnvironmentBOM-false-SAP_ENVIRONMENT_BOM
batchCreation_view.progcal=selectBatch-false-ENT_TL_BATCHMST

