KnwmDevelopedby-required=["cmbKnwmDevelopedby","Select DevelopedBy"]
KnwmApprovedby-required=["cmbKnwmApprovedby","Select ApprovedBy"]
KnwmQuality-required=["txtKnwmQuality","Enter Quality"]
KnwmDescription-required=["txtKnwmDescription","Enter Description"]
KnwdPossiblecauses-required=["txtKnwdPossiblecauses","Enter PossibleCauses"]
KnwdKnowwhy-required=["txtKnwdKnowwhy","Enter  KnowWhy"]
KnwdSolution-required=["txtKnwdSolution","Enter Target Solution"]
KnwdNormalcondition-required=["txtKnwdNormalcondition","Enter NormalCondition"]
KnwmPillarid-required=["cmbKnwmPillarid","Select PillarId"]
KnwmPhenomena-required=["cmbKnwmPhenomena","Select Phenomena"]