Location-required=["cmbLocation","Select Location"]
Environment-required=["cmbEnvironment","Select Environment"]
Environment-invalid=["cmbEnvironment","Invalid Environment for Selected Location"]
Usrm_loginid-required=["txtUserName","Enter User Name"]
Usrm_password-required=["txtPswd","Enter Password"]
Usrm_userlocked=["txtUserName","User Account is Locked"]
Usrm_userremarks=["txtUserName","More than 90 days Not Used,Account is Blocked"]
Usrm_inactive=["txtUserName","Your Validity has Expired"]
Usrm_loginid-invalid=["txtUserName","Invalid User Name"]
#Usrm_loginid-invalid=["txtUserName","No AEDS Login Account"]
Usrm_password-invalid=["txtPswd","Invalid Password"]
Usrm_password-match=["txtcpwdNewpwd","New Password Should not be same as Old Password"]
Usrm_Confpassword-invalid=["txtcpwdConfpwd","Confirm Password Should  be equal as New Password"]
Usrm_Oldpassword-invalid=["txtcpwdOldpwd"," Invalid  Old Password"]
CpwdUsername-required=["txtcpwdUsername","Enter User Name"]
CpwdOldpwd-required=["txtcpwdOldpwd","Enter Old Password"]
CpwdNewpwd-required=["txtcpwdNewpwd","Enter New Password"]
CpwdConfpwd-required=["txtcpwdConfpwd","Enter Confirm Password"]
CpwdNewpwd-min-length=["txtcpwdNewpwd","Password Should Be Minimum 6 Characters"]
EmailId-required=["txtUserName","E-Mail Id not Found, Contact FMS Team to reset your password."]
Usrm_loginid-notFound=["txtUserName","User Name Not Found"]
Usrm_password-change=["btnForgotPwd","You Must Change Your Password"]
CpwdNewpwd-REGEXP=["txtcpwdNewpwd","New-Password should Contains Atleast One Numeric and Alphabet Character"]
Password_Expires=Your Password will Expire in 
Password_Expires-Today=Your Password Expires Today
Password_same=Please Change your password
Password_Expired=Your Password Expired
User_Lock=Your Account Is Locked
Usrm_password-AEDS=No AEDS Login Account!
Password_GracePriodExpires=Your Password is Expired,Your Account Will Lock In
User_LockBy_InvalidPwd=This System will automatically Lock if the login details are not correct 
User_LockBy_Intimate=User Account Will be Lock if the login details are not correct for this Time
WIND_LOGINID_NOTINAPP=["txtUserName","Windows User Name does not exist in Application! Please contact administrator"]
INVALID_WIND_USRORPAWD=["txtUserName","Invalid Windows User Name or Password"]
sepicalchar =["txtcpwdNewpwd","Password Should have at least One Special Character "]
maxpwdlenght =["txtcpwdNewpwd","Password Should Be Maximum  <Minnumber> Character "]
minpwdlenght =["txtcpwdNewpwd","Password Should Be Minimum <Maxnumber> Character "]
minAlphabets =["txtcpwdNewpwd","Password Should have Minimum Alphabets <Minaph> Character "]
minnumeric =["txtcpwdNewpwd","Password Should have Minimum Numeric <Minnum> Number "]
historypwd =["txtcpwdNewpwd","New Password Should not be same as Old Password History"]
Usrm_password-sameusercode =["txtcpwdNewpwd","New Password Should not be same as User Code"]
Usrm_login_validity=["txtUserName","Login account not activated"]
Usrm_login_expired=["txtUserName","Login account expired"]
ADSID=["txtUserName","ADS ID Not Available"]
