MomsDate-required=["dteMomsDate","Select Date"]
MomsShiftid-required=["cmbMomsShiftid","Select Shift"]
MomsSafetytalk-required=["txtMomsSafetytalk","Enter SafetyTalk"]
MomsMeetingno-required=["txtMomsMeetingno"," Enter MeetingNumber "]
MomsMeetingtitle-required=["txtMomsMeetingtitle","Enter MeetingTitle"]
MomsMeetingtype-required=["cmbMomsMeetingtype","Select MeetingType"]
MomsPillarid-required=["cmbMomsPillarid","Select Pillar"]
MomsFactoryid-required=["MomAttfunLocation","Select Location"]
UK_GEN_TL_MOMDTL=["Duplicate Entry"]




