NmrtEmployeeid-required=["cmbNmrtEmployeeid","Select Employee Name"]
NmrtDeptid-required=["cmbNmrtDeptid","Select Department"]
NmrtActionrecommended-required=["txtNmrtActionrecommended","Enter Action Recommended"]
NmrtInvestigation-required=["txtNmrtInvestigation","Enter Investigation"]
NmrtOccurrencedatetime-required=["dteNmrtOccurrencedatetime","Select Date & Time"]
NmrtTargetdate-required=["dteNmrtTargetdate","Select Target Date"]
NmrtSeveritypotentialid-required=["cmbNmrtSeveritypotentialid","Select Severity Potential"]
NmrtProbablerecrate-required=["cmbNmrtProbablerecrate","Select Probable Recurrence Rate"]
NmrtIdentifiedby-required=["cmbNmrtIdentifiedby","Select Prepared By"]
NmrtDescnearmiss-required=["txtNmrtDescnearmiss","Enter Brief Description of Near Miss"]
NmrtResponsibility-required=["cmbNmrtResponsibility","Select Responsibility"]
NmrtOccurrencedatetime-required=["dteNmrtOccurrencedatetime","Select Date of Occurrence"]
NmrtCompletedby-required=["cmbNmrtCompletedby","Select Completed By"]
NmrtCompleteddate-required=["dteNmrtCompleteddate","Select Completed Date"]
NmrtStatus-required=["cmbNmrtStatus","Select Status"]
NEAR_EXIST=["Already Exists"]
			  