Impact=[{"id"\:"","text"\:""},{"id"\:"P","text"\:"P"},{"id"\:"Q", "text"\:"Q"},{"id"\:"C", "text"\:"C"},{"id"\:"D","text"\:"D"},{"id"\:"S", "text"\:"S"},{"id"\:"M", "text"\:"M"},{"id"\:"E", "text"\:"E"}] 
Datatype=[{"id":"I","text":"NUMBER"}]
DatatypeOld=[{"id":"X","text":""},{"id":"I","text":"NUMBER"},{"id":"F", "text":"DECIMAL"},{"id":"D", "text":"DATE"},{"id":"S", "text":"STRING"}]
SourceofKPI=[{"id":"","text":""},{"id":"VC","text":"VOICE OF CUSTOMER"},{"id":"TD", "text":"TOP DRIVEN"},{"id":"SD", "text":"SELF DRIVEN"}]
Frequency=[{"id":"","text":""},{"id":"D","text":"DAILY"},{"id":"W","text":"WEEKLY"},{"id":"M", "text":"MONTHLY"},{"id":"Q","text":"QUARTERLY"},{"id":"H", "text":"HALF YEARLY"},{"id":"Y", "text":"YEARLY"}]
Frequency1=[{"id":"","text":""},{"id":"D","text":"BELOW MONTHLY"},{"id":"M", "text":"MONTHLY AND ABOVE"}]
TypofInput=[{"id":"","text":""},{"id":"M","text":"MANUAL"},{"id":"A", "text":"AUTO"},{"id":"X", "text":"DATA UPLOAD"}]
IndicatorType=[{"id":"","text":""},{"id":"KPI","text":"KPI"},{"id":"KPIV", "text":"KPIV"},{"id":"KPOV", "text":"KPOV"}]
CalcType=[{"id":"A", "text":"Average"},{"id":"S","text":"Sum"}, {"id":"X","text":""}]
