OplmDate-LECD=["dteoplmDate","OPL Date Should be lesser than equal to Current Date"]
OplmCellid-required=["cell","Select JH"]
OplmMachineid-required=["cmboplmMachineid","Select Equipment"]
OplmTheme-required=["txtoplmTheme","Enter Theme"]
OplmLesson-required=["txtoplmLesson","Enter Lesson"]
OplmApprovedid-required=["cmboplmApprovedid","Select Approved by"]
OplmPrepareddate-LECD=["dteoplmPrepareddate","Prepared Date Cannot be less  than current Date"]
#OplmApproveddate-LE=["dteoplmApproveddate","Approved Date Cannot be less than Prepared Date"]
classification-required-AtLeastOne=["chkClassificationT","Select Classification"]
OplcName-required=["txtOplcName","Enter Name"]
OplcCode-required=["txtOplcCode","Enter Code"]
#OplmRelated-required=["cmboplmRelated","Select Related to"]
OplmMouldid-required=["cmboplmMouldid","Select Mould"]
approve_DelMode=["OPL is approved, Can not be deleted."]
approve_ModifyMode=["OPL is approved, Can not be Modified."]
OplmPreparedid-required=["cmboplmPreparedid","Select Prepared By"]
UK_OPL_TL_MST=["This Record is already exist"]