PrlmEntrydate-required=["hdnPrlmEntrydate","Select Date"]
Machineid-required=["cmbmachineid","Select Machine"]
Productid-required=["","Select Product"]
Trimmingqty-required=["","Enter Trimming Qty"]
Expansionqty-required=["","Enter Expansion Qty"]
Actualcycletime-required=["","Enter Actual Time"]
Producedqty-required=["","Enter Produce Qty"]
#Wno-required=["txtPtwowno","Enter Work Order No"]
PlrkLossid-required=["","Select Loss"]
PlrkReasonid-required=["","Select Phenomena"]
PlrkMinutes-required=["","Enter Time/Qty"]
PlrkInstance-required=["","Enter No. of Instance"]
PopdPlemployeeid-required=["","Select Operator"]
view_Mode=["Data cannot be saved in view mode"]
view_DelMode=["Data cannot be deleted in view mode"]
view_LossExists=["Loss Exists, Can not be Deleted"]
view_LockDelete=["Delete is Locked"]
PK_PCS_TL_OPERATORDTL=["Operator Name Already Exists"]
productionTime_Greate=["Production Time can not be greater than Available Time"]
prd_Exists=["Product exists"] 
LOSSEXIST=["Loss exists"] 

#LOSS CAPTURE
PlosFlid-required=["","Select Function Location"]
PlosDate-required=["","Select Date"]
PlosShiftid-required=["","Select Shift"]
PlosFromtime-required=["","Enter From Time"]
PlosTotime-required=["","Enter To Time"]
PlosLosstime-required=["","Enter Loss time"]
PlosLossreason-required=["","SelectLoss Reason"]
PlosLossid-required=["","Select Loss"]
PlosTradeid-required=["","Select Trade"]