BnprProposedphn-required=["txtbnprProposedphn","Enter Phenomena"]
BnprProposedcause-required=["txtbnprProposedcause","Enter Cause"]
BnprIscausereq-required=["chkbnprIscausereq"]
UK_BPHM_PHENOMENANAME=["Phenomena Name already Exist"]

