PjobFlid-required=["PlannedJobDescfunlocation","Select JH in Functional Location"]
PjobEmployeeid-required=["cmbPjobEmployeeid","Select Employee"]
#PjobDate-LECD=["dtePjobDate","Date Should not be Greater than Current Date"]
PjobDate-LECD=["dtePjobDate","Date Should not be Greater than Current Date"]
PjobFollowUpDate-LE=["dtePjobFollowUpDate","Follow-Up Date Should be Greater than Observed Date"]
PjobDate-required=["dtePjobDate","Select Observed Date"]
PjobTaskObserved-required=["txtPjobTaskObserved","Enter Task Observed"]
PjobType-required=["cmbPjobType","Select Type of Observation"]
PjobNotification-required=["cmbPjobNotification","Select Notification"]
PjobReasonid-required=["cmbPjobReasonid","Select Reason"]
#PjobFollowUpAction-required=["txtPjobFollowUpAction","Enter Follow up Action"]
UK_EMPLOYEE=["Employee Already Mapped"]