RasmFlid-required=["txtRasmFlid","Select Functional Location"]
RasmArea-required=["txtRasmArea","Enter Area"]
RasmTitle-required=["txtRasmTitle","Enter Title"]
RasmDate-required=["dteRasmDate","Enter Date"]
RasmDate-LECD=["dteRasmDate","Risk Assessment Date Should Be Less Than Or Equal To Current Date"]
RasmPreparedby-required=["cmbRasmPreparedby","Select Prepared By"]
DramDate-required=["dteDramDate","Enter Date"]
DramDate-LECD=["dteDramDate","De-Risk Assessment Date Should Be Less Than Or Equal To Current Date"]
DramPreparedby-required=["cmbDramPreparedby","Select Prepared By"]
FK_DRAD_RASD_KEYID=["De-Risk Already Done For This Risk Assessment"]