SafmItem-required=["txtSafmItem","Enter the the item "]
SafmToolsused-required=["txtSafmToolsused","Enter the tools used"]
SafmHowtocheck-required=["txtSafmHowtocheck","Enter the how to check "]
SafmCheckpoint-required=["txtSafmCheckpoint","Enter The Check Point"]
SafmFlid-required=["frmsafetyfunloc","Select the Functional Location"]