SermReportedby-required=["cmbSermReportedby","Select ReportedBy"]
SermDescription-required=["txtSermDescription","Enter Description"]
SermFormname-required=["txtSermFormname","Enter Form Name"]
SermBookedby-required=["cmbSermBookedby","Select BookedBy"]
SermModule-required=["cboSermModule","Select Module"]
SermApprovedby-required=["cmbSermApprovedby","Select Approved By"]
SermApproveddate-required=["dteSermApproveddate","Select Approved Date"]
SermApprovalremarks-required=["txtSermApprovalremarks","Enter Remarks"]
SepdTargetdate-required=["dteSepdTargetdate","Select Target date"]
SepdAlloteddate-required=["dteSepdAlloteddate","Select Alloted date"]
SepdCompleteddate-required=["dteSepdReceiveddate","Select Received date"]
SepdAllotedto-required=["txtSepdAllotedto","Select Alloted to"] 
SepdReceivedby-required=["txtSepdReceivedby","Select received by"]
SepdStatus-required=["cboSepdStatus","Select Status"]
SepdAlloteddate-LE=["dteSepdAlloteddate","Allocated date must be greater than Received Date "]
SepdCompleteddate-LE=["dteSepdCompleteddate","Completed date must be greater than Allocated Date "]
mailNotSent=["Mail Not Sent"]



