SlamDate-required=["dteSlamDate","Enter SLA Date"]
SlamFromdptid-required=["cmbSlamFromdptid","Select Between From"]
SlamTodptid-required=["cmbSlamTodptid","Select And"]
SladProductid-required=["cmbSladProductid","Select Product"]
SladUomid-required=["cmbSladUomid","Select UoM"]
SladMutualtarget-required=["txtSladMutualtarget","Enter Target"]
SladMutualmin-required=["txtSladMutualmin","Enter min"]
SladMutualmax-required=["txtSladMutualmax","Enter Max"]
SladQualitycharacter-required=["txtSladQualitycharacter","Enter Quality Characteristics"]
SladMutualmax-GE=["txtSladMutualmax","Maximum Value Should Be Greater Than Minimum Value"]
SladMutualmin-LE=["txtSladMutualmin","Minimum Value Should Be Lesser Than Maximum Value"]
SladMutualtarget-LE=["txtSladMutualmax","Target Value Should Be Lesser Than Maximum Value"]
SladMutualtarget-GE=["txtSladMutualmin","Target Value Should Be Greater Than Minimum Value"]
SladFrequency-required=["cmbsladFrequency","Select Frequency"]
SladEffectivedate-required=["dteSladEffectivedate","Enter Effective Date"]
SlamApprovedby-required=["cmbslamApprovedby","Select Approved by"]
SlamApproveddate-required=["dteslamApproveddate","Select Approved date"]
SlamStatus-required=["chkslaReject","Select Status"]
UK_SLAM_FROMDPTIDTODPTID=["Already SLA is Defined between this two DMT"]
SlamDate-GECD=["dteSlamDate","SLA Date Should  not Greater then Current date"]
SladEffectivedate-LECD=["dteSladEffectivedate","Effective Date Should  not lesser then Current date"]
SlamApproveddate-LECD=["dteslamApproveddate","Approved Date Should  not lesser then Current date"]
SlamSource-required=["chkSlamSource","Select Source"]
SladAdherenceperc-required=["txtsladAdherenceperc","Enter Adherence Percentage"]
SLAEntryvald =[""," Can Not able to Modify This SLA Definition Because SLA Entry had Done "]
SlamApproveddate-LE=["dteslamApproveddate","Approved Date Should  not lesser then sla date"]

