SprmPartno-required=["cmbsprmPartno","Enter Part No"]
SprmPartname-required=["txtsprmPartname","Enter Spares Description"]
SprmSource-required=["cmbsprmFactoryid","Select Source"]
SprmType-required=["cmbsprmType","Select Type"]
SprmCriticalityid-required=["cmbsprmCriticalityid","Select Criticality"]
SprmClassificationid-required=["cmbsprmClassificationid","Select Classification"]
SprmCategoryid-required=["cmbsprmCategoryid","Select Category"]
SprmAbcclass-required=["cmbsprmAbcclass","Select ABC Class"]
SprmMake-required=["cmbsprmMake","Select Make"]
SprmModel-required=["cmbsprmModel","Select Model"]
SprmSpecification-required=["txasprmSpecification","Enter Specification"]
SprmReorderlevel-required=["txtsprmReorderlevel","Enter Reorder Level"]
SprmReorderqty-required=["txtsprmReorderqty","Enter Reorder Qty"]
SprmMaxinventorylevel-required=["txtsprmMaxinventorylevel","Enter Max Inventory Level"]
SprmLeadtimeinternal-required=["txtsprmLeadtimeinternal","Enter Lead Time Internal"]
SprmLeadtimeexternal-required=["txtsprmLeadtimeexternal","Enter Lead Time External"]
SprmShelflifeitem-required=["cmbsprmShelflifeitem","Enter Shelf Life Item"]
SprmSupplierpartno-required=["txtsprmSupplierpartno","Select Supplier Part No"]
UK_SPRM_PARTNO=["Part No already Exist"]
