StwsProcess-required=["cmbStwsProcess","Select Process"]
StwsBudgetedtime-required=["txtStwsBudgetedtime","Select Budget Time "]
StwsDate-required=["dteStwsDate","Select  Date"]
StwsBy-required=["cmbStwsBy","Select by "]
StwsApprovedby-required=["cmbStwsApprovedby","Select Approved by"]
StwsFlid-required=["txtStwsFlid","Select Function Location"]
StwsCycletime-required=["txtStwsCycletime","Enter Sample Budgeted Time"]


