TmhiName-required=["txtTmhiName","Enter Team Name"]
TmhiCode-required=["txtTmhiCode","Enter Team Code"]
TmhiDescription-required=["txtTmhiDescription","Enter Team Description"]
TmelTmhiKeyid-required=["","Select Team"]
TmelEmpid-required=["cmbTmelEmpid","Select Employee"]
TmfmTmhiKeyid-required=["","Select Team"]
#view_Mode=["Data cannot be saved in view mode"]
UK_TEAM_EMPID=["Employee Name Already Exists"]
FK_TMEL_TMHI_KEYID=["Team Can not Delete, team had Employess"]
EMPLOYEE_EXISTS=["Can't Delete Team, Team had Employee's "]
SUBTEAM_EXISTS=["Can't Delete Team, Sub Team found "]
UK_TEAM_FUN_KEYID=["Already Mapped"]
ASSTLEADEREXISTS=["Maximum 2 Assistant Leaders can be assigned"]
LEADEREXISTS=["Team already having Leader"]