TopiName-required=["txtTopiName","Enter Name"]
TopiType-required=["cboTopiType","Select KSA"]
#TopiSpokeid-required=["cmbTopiSpokeid","Select Criteria"]
TopiEvaluationtypeid-required=["cmbTopiEvaluationtypeid"," Select Evaluation Type "]
TopiTrainingmode-required=["cmbTopiTrainingmode"," Select Training Mode "]
TopiRelatedto-required=["cboTopiRelatedto," Select Type "]
RoleKeyid-required=["cmbRoleKeyid","Select Unique Position"]
TopiTrainingmode-required=["cmbTopiTrainingmode","Select Training Mode"]
UK_TOPI_NAME=["Data already Exists"]