UswpTargetdate-LE=["dteUswpTargetdate","Target date must be Greater than Current Date"]
UswpCompletedon-LE=["dteUswpCompletedon","Completed On must be Greater than Identified Date"]
UswpIdentifiedby-required=["cmbUswpIdentifiedby","Select Identified by"]
UswpResponsibility-required=["cmbUswpResponsibility","Select Responsibility"]
UswpUnsafeworkpractice-required=["txtUswpUnsafeworkpractice","Enter UnsafeWork Practices"]
UswpCountermeasure-required=["txtUswpCountermeasure","Enter CounterMeasure"]
UswpCompletedby-required=["cmbUswpCompletedby","Select Completed by"]
UswpStatus-required=["cmbUswpStatus","Select Status"]
UswpActiontaken-required=["txtUswpActiontaken","Enter Action to be taken"]
UswpFlid-required=["cmbUswpFlid","Select Functional Location"]
