VcclFlid-required=["txtVcclFlid","Select Function Location"]
VcclTitle-required=["cmbVcclTitle","Select Title"]
VcclDate-required=["dteVcclDate","Select Date"]
VcclEmployeeid-required=["cmbVcclEmployeeid","Select Prepared by"]
VcclApprovedby-required=["cmbVcclApprovedby","Select Approved by"]
