VsomFlnid-required=["frmVisualSopmomfunLocationValues","Specify Functional Location"]
VsomOperation-required=["txtVsomOperation","Specify Operation"]
VsomSafetyinstruction-required=["txtVsomSafetyinstruction","Specify Safety Instruction "]
VsomPreparedby-required=["txtVsomPreparedby","Specify Prepared by"]
VsomIssuedby-required=["txtVsomIssuedby","Specify Issued by"]


