#WomsRelatedto-required=["cmbwomsRelatedto","Select Related To"]
WomsLoss-required=["cmbwomsLoss","Select Loss"]
WomsMachineid-required=["cmbwomsMachineid","Select Equipment"]
WomsOccurreddate-required=["dtewomsOccurreddate","Select Occured Date"]
WomsReporteddate-required=["dtewomsReporteddate","Select Reported Date"]
WomsAccepteddate-required=["dtewomsAccepteddate","Select Accepted Date"]
ReportedDateTime-LE=["dtewomsReporteddate","Reported date must be greater than Occurred Date"]
OccuredDateTime-LECD=["dtewomsOccurreddate","Occured Date & Time should not be greater than current date & time"]
AllottedDateTime-LE=["dtewomsAllotteddate"," Allotted date must be greater than Received Date"]
AllottedDateTime-LECD=["dtewomsAllotteddate","Allotted Date & Time should not be greater than current date & time"]
AcceptedDateTime-LE=["dtewomsAccepteddate"," Accepted Date & Time should not be greater than Allotted Date"]
WomsAccepteddate-LE=["dtewomsAccepteddate"," Received Date & Time should be greater than Reported Date & time"]
AcceptedDateTime-LECD=["dtewomsAccepteddate","Accepted Date & Time should not be greater than current date & time"]
WomsReporteddate-LE=["dtewomsReporteddate","Reported date must be greater than Occurred Date"]
WomsOccurreddate-LECD=["dtewomsOccurreddate","Select Occured date"]
WomsPriority-required=["cmbwomsPriority","Select Priority"]
WomsProcessId-required=["cmbwomsProcessId","Select Process"]
WomsActivitytype-required=["cmbwomsActivitytype","Select Activity Type"]
WomsActtype-required=["cmbwomsActtype","Select Activity Type"]
WomsProblem-required=["txtwomsProblem","Enter Problem"]
#WomsMouldid-required=["cmbwomsMouldid","Select Mould"]
WomsAssemblyid-required=["cmbwomsAssemblyid","Select Assembly"]
WomsFailuretypeid-required=["cmbwomsFailuretypeid","Select Failure Type"]
WomsTradeid-required=["cmbwomsTradeid","Select Maint. Section"]
WomsPhenomenaid-required=["cmbwomsPhenomenaid","Select Phenomena"]
WomsTempfield10-required=["cmbwomsTempfield10","Select Classification"]
WomsBookedby-required=["cmbwomsBookedby","Select Booked By"]
WomsRequestapproved-required=["hdnwomsRequestapproved","Select Approval/Cancel"]
WomsRequestapproveddate-required=["dtewomsRequestapproveddate","Select Approval Date"]
WomsRequestapproveddate-LE=["dtewomsRequestapproveddate","Request Approved date must be greater than Reported Date "]
Reporteddateflag-LECD=["WomsOccurreddate","Select Reported date"]
WomsRequestapprovedby-required=["cmbwomsRequestapprovedby","Select Approval By"]
WomsRequestapprovremarks-required=["txtwomsRequestapprovremarks","Enter Approval Remarks"]

WomsAcceptedby-required=["cmbwomsAcceptedby","Select By"]
WomsProductionapproval-required=["chbwomsProductionapproval","Select Production Approval"]
WomsProposedstartdate-required=["dtewomsProposedstartdate","Select Proposed Start Date"]
WomsProposedenddate-required=["dtewomsProposedenddate","Select Proposed End Date"]

Requestapproveddateflag-LECD=["WomsOccurreddate","Select Request Approved date"]
WomsProposedstartdate-LE=["dtewomsProposedstartdate","Proposed From date must be greater than Accepted Date "]

WomsProposedenddate-LE=["dtewomsProposedenddate","Proposed To date must be greater than Proposed From Date "]
WomsProposedstartdate-LECD=["WomsOccurreddate","Select Proposed End date"]
WomsSafetypermitsrequried-required=["hdnwomsSafetypermitsrequried","Select Permit Required"]
WomsAcceptedremarks-required=["txtwomsAcceptedremarks","Enter Remarks"]
WomsRescheduledate-required=["dtewomsRescheduledate","Select Reschedule Date"]
WomsRescheduleby-required=["cmbwomsRescheduleby","Select Rescheduled By"]
WomsRescheduleflag-required=["hdnwomsRescheduleflag","Select Accept/Reschedule"]
WomsReschedulestartdate-required=["dtewomsReschedulestartdate","Select Reschedule Start Date"]
WomsRescheduleenddate-required=["dtewomsRescheduleenddate","Select Reschedule End Date"]
WomsRescheduleremarks-required=["txtwomsRescheduleremarks","Enter Reschedule Remarks"]
WomsRescheduledate-LE=["dtewomsRescheduledate","Reschedule date must be greater than Accepted Date "]
Accepteddateflag-LECD=["WomsOccurreddate","Select Reschedule date"]
WomsReschedulestartdate-LE=["dtewomsReschedulestartdate","Reschedule From date must be greater than Reschedule Date "]
WomsRescheduledate-LECD=["WomsOccurreddate","Select Reschedule From date"]
WomsRescheduleenddate-LE=["dtewomsRescheduleenddate","Reschedule To date must be greater than Reschedule From Date "]
WomsReschedulestartdate-LECD=["WomsOccurreddate","Select Reschedule To date"]
WomsAllotteddate-required=["dtewomsAllotteddate","Select Allotted Date"]
WomsAllotteddate-LE=["dtewomsAllotteddate","Allotted date must be greater than Reported Date "]
Rescheduledateflag-LECD=["WomsOccurreddate","Select Allotted date"]
WomsAllottedto-required=["cmbwomsAllottedto","Select Allotted To"]
WomsAllottedremarks-required=["txtwomsAllottedremarks","Enter Allotted Remarks"]
WomsDoneby-required=["cmbwomsDoneby","Select Completed By"]
WomsFinalactivitytype-required=["cmbwomsFinalactivitytype","Select Activity Type"]
WomsWorkstartdate-required=["dtewomsWorkstartdate","Select Work Start Date"]
WomsWorkenddate-required=["dtewomsWorkenddate","Select Work End Date"]
WomsWoapprovaldate-required=["dtewomsWoapprovaldate","Select Work Approval Date"]
WomsWoapprovalby-required=["cmbwomsWoapprovalby","Select Work Approval By"]
WomsMachinereleaseddate-required=["dtewomsMachinereleaseddate","Select Machine Release Date"]
WomsWorkstartdate-LE=["dtewomsWorkstartdate","Work Start date must be greater than Allotted Date "]
Allotteddateflag-LECD=["WomsOccurreddate","Select Work Start date"]
WomsWorkenddate-LE=["dtewomsWorkenddate","Work End date must be greater than Work Start Date "]
WomsWorkstartdate-LECD=["WomsOccurreddate","Select Work End date"]
WomsWoapprovaldate-LE=["dtewomsWoapprovaldate","Work Approval date must be greater than Work End Date "]
WomsWorkenddate-LECD=["WomsOccurreddate","Select Work Approval date"]
WomsMachinereleaseddate-LE=["dtewomsMachinereleaseddate","Machine Release date must be greater than Work Approval Date "]
WomsWoapprovaldate-LECD=["WomsOccurreddate","Select Machine Release date"]
WomsMachinereleaseby-required=["cmbwomsMachinereleaseby","Select Machine Release By"]
WomsExceptedreturndate-required=["dtewomsExceptedreturndate","Select Completed On"]
WomsRemarks-required=["txtwomsRemarks","Enter Remarks"]
WomsProductionby-required=["cmbwomsProductionby","Select Production By"]
WomsProductionstartdate-required=["dtewomsProductionstartdate","Select Production On"]
WomsProductionstartdate-LE=["dtewomsProductionstartdate","Production On must be greater than Work End Date "]
Completeddateflag-LECD=["WomsOccurreddate","Select Production On"]
WomsProductionremarks-required=["txtwomsProductionremarks","Enter Remarks"]
prodAvlTime=["PCS Entry Exists for this Machine.No Unreported Time"]
msrOverlap=["MSR Overlap"]
prodExist=["PRODUCTION EXISTS!"]
timeExceeds=["TIME SELECTED EXCEEDS THE LIMIT"]
MAXBOOKINGDATE=["OCCURRED DATE EXCEEDS THE LIMIT"]
mouldUnloaded=["This Mould is Unloaded Already"]
notiFailed=["This document is already submitted to SAP and waiting for response.Please try again later."]
orderFailed=["This order is already submitted to SAP and waiting for response.Please try again later."]
onFailed=["This document is already submitted to SAP and waiting for response.Please try again later."]
